import argparse
import csv
from pathlib import Path
from typing import Dict, List

import numpy as np

from learning_utils import load_embedding_archive
from script_utils import LEARNING_ROOT, ensure_dir, require_file, write_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compute stage-wise diagnostics for CLIP embeddings.")
    parser.add_argument(
        "--embeddings-npz",
        default=str(LEARNING_ROOT / "embeddings" / "clip_embeddings_all.npz"),
        help="Path to embedding .npz generated by extract_clip_embeddings.py",
    )
    parser.add_argument(
        "--output-dir",
        default=str(LEARNING_ROOT / "diagnostics"),
        help="Output directory for diagnostics artifacts",
    )
    return parser.parse_args()


def cosine_matrix(embeddings: np.ndarray) -> np.ndarray:
    norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
    safe = np.maximum(norms, 1e-12)
    x = embeddings / safe
    return x @ x.T


def stage_stats(cos: np.ndarray, stage_indices: np.ndarray) -> Dict[str, Dict[str, float]]:
    unique_stages = sorted(int(v) for v in np.unique(stage_indices))
    stats: Dict[str, Dict[str, float]] = {}

    for stage in unique_stages:
        same = np.where(stage_indices == stage)[0]
        other = np.where(stage_indices != stage)[0]

        intra_values = []
        if same.size >= 2:
            intra = cos[np.ix_(same, same)]
            mask = ~np.eye(intra.shape[0], dtype=bool)
            intra_values = intra[mask]

        inter_values = []
        if same.size > 0 and other.size > 0:
            inter = cos[np.ix_(same, other)]
            inter_values = inter.ravel()

        intra_mean = float(np.mean(intra_values)) if len(intra_values) > 0 else float("nan")
        inter_mean = float(np.mean(inter_values)) if len(inter_values) > 0 else float("nan")
        separability = intra_mean - inter_mean if np.isfinite(intra_mean) and np.isfinite(inter_mean) else float("nan")

        stats[str(stage)] = {
            "num_samples": int(same.size),
            "intra_cosine_mean": intra_mean,
            "inter_cosine_mean": inter_mean,
            "separability_margin": separability,
        }

    return stats


def nearest_neighbor_stage_accuracy(cos: np.ndarray, stage_indices: np.ndarray) -> float:
    n = cos.shape[0]
    if n < 2:
        return float("nan")

    work = cos.copy()
    np.fill_diagonal(work, -np.inf)
    nn_idx = np.argmax(work, axis=1)
    return float(np.mean(stage_indices[nn_idx] == stage_indices))


def centroid_similarity_matrix(embeddings: np.ndarray, stage_indices: np.ndarray) -> Dict[str, object]:
    unique_stages = sorted(int(v) for v in np.unique(stage_indices))
    centroids = []
    for stage in unique_stages:
        vecs = embeddings[stage_indices == stage]
        cent = vecs.mean(axis=0)
        norm = np.linalg.norm(cent)
        if norm > 0:
            cent = cent / norm
        centroids.append(cent)

    c = np.stack(centroids, axis=0)
    sim = c @ c.T
    return {
        "stages": unique_stages,
        "matrix": sim,
    }


def write_similarity_csv(path: Path, stages: List[int], matrix: np.ndarray) -> None:
    ensure_dir(path.parent)
    header = ["stage"] + [str(s) for s in stages]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        for i, s in enumerate(stages):
            writer.writerow([s] + [f"{matrix[i, j]:.6f}" for j in range(len(stages))])


def intra_cosine_series(per_stage: Dict[str, Dict[str, float]]) -> Dict[str, List[float]]:
    stages = sorted(int(stage) for stage in per_stage.keys())
    values = [float(per_stage[str(stage)]["intra_cosine_mean"]) for stage in stages]
    return {"stages": stages, "values": values}


def main() -> None:
    args = parse_args()
    npz_path = Path(args.embeddings_npz)
    out_dir = Path(args.output_dir)
    ensure_dir(out_dir)

    require_file(npz_path, "Embeddings file")
    data = load_embedding_archive(npz_path)
    embeddings = data["embeddings"]
    stage_indices = data["stage_indices"]

    cos = cosine_matrix(embeddings)
    per_stage = stage_stats(cos, stage_indices)
    nn_acc = nearest_neighbor_stage_accuracy(cos, stage_indices)

    centroid = centroid_similarity_matrix(embeddings, stage_indices)
    stages = centroid["stages"]
    matrix = centroid["matrix"]
    intra = intra_cosine_series(per_stage)

    write_similarity_csv(out_dir / "stage_centroid_cosine.csv", stages, matrix)

    summary = {
        "embeddings_file": str(npz_path),
        "num_samples": int(embeddings.shape[0]),
        "embedding_dim": int(embeddings.shape[1]),
        "nearest_neighbor_same_stage_accuracy": nn_acc,
        "per_stage": per_stage,
        "centroid_stages": stages,
        "centroid_cosine_matrix": matrix.tolist(),
    }
    write_json(out_dir / "embedding_diagnostics.json", summary)

    # Optional heatmap export if matplotlib exists.
    try:
        import matplotlib.pyplot as plt

        fig = plt.figure(figsize=(7, 6))
        ax = fig.add_subplot(1, 1, 1)
        im = ax.imshow(matrix, vmin=0, vmax=1.0, cmap="viridis")
        ax.set_title("Stage Centroid Cosine Similarity")
        ax.set_xticks(range(len(stages)))
        ax.set_yticks(range(len(stages)))
        ax.set_xticklabels(stages)
        ax.set_yticklabels(stages)
        fig.colorbar(im, ax=ax)
        fig.tight_layout()
        fig.savefig(out_dir / "stage_centroid_cosine.png", dpi=150)
        plt.close(fig)

        fig = plt.figure(figsize=(8, 4.5))
        ax = fig.add_subplot(1, 1, 1)
        bars = ax.bar(intra["stages"], intra["values"], color="#1f77b4", width=0.75)
        ax.set_title("Per-Stage Intra Cosine Similarity")
        ax.set_xlabel("Stage")
        ax.set_ylabel("Mean Intra-Stage Cosine")
        ax.set_xticks(intra["stages"])
        ax.set_ylim(0.0, 1.0)
        ax.grid(axis="y", linestyle="--", alpha=0.35)

        for bar, value in zip(bars, intra["values"]):
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                min(value + 0.015, 0.99),
                f"{value:.3f}",
                ha="center",
                va="bottom",
                fontsize=8,
            )

        fig.tight_layout()
        fig.savefig(out_dir / "stage_intra_cosine.png", dpi=150)
        plt.close(fig)
    except Exception:
        pass

    print("Embedding diagnostics complete")
    print(f"Samples:      {summary['num_samples']}")
    print(f"NN accuracy:  {summary['nearest_neighbor_same_stage_accuracy']:.4f}")
    print(f"Output dir:   {out_dir}")


if __name__ == "__main__":
    main()
