import argparse
import shutil
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import torch
from PIL import Image, ImageDraw, ImageOps

from learning_utils import (
    TransitionMLP,
    PixelDecoderUNet,
    StructuralLayerUNet,
    compose_white_layer,
    default_device,
    embed_image_with_clip,
    embed_image_with_dino,
    image_to_tensor,
    load_embedding_archive,
    load_model_config,
    load_transition_mlp_checkpoint,
    tensor_to_pil,
)
from script_utils import LEARNING_ROOT, ensure_dir, read_csv_rows, require_file, write_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Roll a rough owl sketch forward through latent stages.")
    parser.add_argument("input_image", help="Path to a rough sketch image")
    parser.add_argument(
        "--checkpoint",
        default=str(LEARNING_ROOT / "ar_baseline" / "best_model.pt"),
        help="Path to trained transition baseline checkpoint",
    )
    parser.add_argument(
        "--metrics-json",
        default=str(LEARNING_ROOT / "ar_baseline" / "metrics.json"),
        help="Metrics JSON written by train_transition_baseline.py",
    )
    parser.add_argument(
        "--embeddings-npz",
        default=str(LEARNING_ROOT / "embeddings" / "clip_embeddings_all.npz"),
        help="Path to embedding .npz generated by extract_clip_embeddings.py",
    )
    parser.add_argument(
        "--manifest-frames",
        default=str(LEARNING_ROOT / "manifest_frames.csv"),
        help="Path to frame manifest CSV from build_manifest.py",
    )
    parser.add_argument(
        "--output-dir",
        default=str(LEARNING_ROOT / "inference"),
        help="Output directory for rollout artifacts",
    )
    parser.add_argument(
        "--render-mode",
        choices=["retrieval", "pixel"],
        default="retrieval",
        help="Use nearest-neighbor retrieval or the trained pixel decoder for stage images",
    )
    parser.add_argument(
        "--pixel-decoder-checkpoint",
        default=str(LEARNING_ROOT / "pixel_decoder" / "best_pixel_decoder.pt"),
        help="Path to trained pixel decoder checkpoint from train_pixel_decoder.py",
    )
    parser.add_argument(
        "--structural-decoder-checkpoint",
        default=str(LEARNING_ROOT / "structural_decoder" / "best_structural_decoder.pt"),
        help="Path to trained structural layer decoder checkpoint",
    )
    parser.add_argument(
        "--disable-structural-decoder",
        action="store_true",
        help="In pixel mode, skip structural layer decoder and use the pixel decoder for all stages",
    )
    parser.add_argument(
        "--structural-until-stage",
        type=int,
        default=4,
        help="Use structural decoder for predicted stages up to and including this stage",
    )
    parser.add_argument(
        "--structural-threshold",
        type=float,
        default=None,
        help="Override structural layer probability threshold from checkpoint",
    )
    parser.add_argument(
        "--save-retrieval-fallback",
        action="store_true",
        help="In pixel mode, also save nearest retrieved stage images for side-by-side comparison",
    )
    parser.add_argument(
        "--embedding-backend",
        choices=["auto", "clip", "dino"],
        default="auto",
        help="Encoder family used to create the embedding archive and encode the input sketch.",
    )
    parser.add_argument("--model-id", default="", help="Encoder model id. Leave empty to infer from metrics or backend defaults.")
    parser.add_argument("--device", default=default_device(), help="Inference device")
    parser.add_argument("--start-stage", type=int, default=0, help="Stage index represented by the input sketch")
    parser.add_argument(
        "--end-stage",
        type=int,
        default=-1,
        help="Final stage index to roll out to (-1 uses highest stage available in retrieval bank)",
    )
    parser.add_argument(
        "--retrieval-split",
        choices=["train", "val", "test", "all"],
        default="train",
        help="Which split to retrieve nearest stage images from",
    )
    parser.add_argument(
        "--use-retrieved-embedding",
        action="store_true",
        help="Snap each step to the retrieved embedding before predicting the next stage",
    )
    parser.add_argument("--retrieval-topk", type=int, default=5, help="Number of nearest candidates to consider before reranking")
    parser.add_argument("--retrieval-beam-width", type=int, default=3, help="Beam width for rollout-time retrieval reranking")
    parser.add_argument(
        "--retrieval-consistency-weight",
        type=float,
        default=0.15,
        help="Weight for consistency with the previously selected retrieved embedding",
    )
    parser.add_argument(
        "--retrieval-anchor-weight",
        type=float,
        default=0.05,
        help="Weight for consistency with the original input embedding",
    )
    parser.add_argument(
        "--early-retrieval-max-stage",
        type=int,
        default=3,
        help="Predicted stages up to and including this index use the early-stage retrieval reranker settings",
    )
    parser.add_argument(
        "--early-retrieval-topk",
        type=int,
        default=10,
        help="Top-k candidate pool to use for early-stage retrieval reranking",
    )
    parser.add_argument(
        "--early-retrieval-consistency-multiplier",
        type=float,
        default=2.0,
        help="Multiplier on retrieval consistency weight for early stages",
    )
    parser.add_argument(
        "--early-retrieval-anchor-multiplier",
        type=float,
        default=3.0,
        help="Multiplier on retrieval anchor weight for early stages",
    )
    parser.add_argument(
        "--early-retrieval-source-weight",
        type=float,
        default=0.15,
        help="Extra weight on similarity to the current source embedding during early-stage reranking",
    )
    return parser.parse_args()


def resolve_embedding_backend(requested_backend: str, model_config: Dict[str, object], embeddings_path: Path) -> str:
    if requested_backend != "auto":
        return requested_backend

    training_config = model_config.get("training_config", {})
    if isinstance(training_config, dict):
        saved_backend = str(training_config.get("embedding_backend", "")).strip().lower()
        if saved_backend in {"clip", "dino"}:
            return saved_backend

    name = embeddings_path.name.lower()
    if "dino" in name:
        return "dino"
    if "clip" in name:
        return "clip"
    return "clip"


def resolve_model_id(requested_model_id: str, embedding_backend: str, model_config: Dict[str, object]) -> str:
    if str(requested_model_id).strip():
        return str(requested_model_id).strip()

    training_config = model_config.get("training_config", {})
    if isinstance(training_config, dict):
        saved_model_id = str(training_config.get("model_id", "")).strip()
        if saved_model_id:
            return saved_model_id

    if embedding_backend == "dino":
        return "facebook/dinov2-base"
    return "openai/clip-vit-base-patch32"


def load_frame_bank(npz_path: Path, manifest_path: Path, retrieval_split: str) -> Dict[int, Dict[str, object]]:
    data = load_embedding_archive(npz_path, normalize=True)
    embeddings = data["embeddings"]
    stems = data["stems"]
    stage_indices = data["stage_indices"]
    image_paths = data["image_paths"]
    splits = data["splits"]

    manifest_lookup = {
        (str(row["stem"]), int(row["stage_idx"])): row
        for row in read_csv_rows(manifest_path, description="Frame manifest")
    }

    by_stage: Dict[int, Dict[str, object]] = {}
    for stem, stage_idx, image_path, split, emb in zip(stems, stage_indices, image_paths, splits, embeddings):
        stage = int(stage_idx)
        split_name = str(split)
        if retrieval_split != "all" and split_name != retrieval_split:
            continue

        meta = manifest_lookup.get((str(stem), stage), {})
        stage_bucket = by_stage.setdefault(stage, {"embeddings": [], "records": []})
        stage_bucket["embeddings"].append(emb)
        stage_bucket["records"].append(
            {
                "stem": str(stem),
                "stage_idx": stage,
                "split": split_name,
                "image_path": str(image_path),
                "frame_key": meta.get("frame_key", f"{stem}_stage{stage:02d}"),
            }
        )

    for stage, bucket in by_stage.items():
        if len(bucket["embeddings"]) == 0:
            raise RuntimeError(f"No retrieval candidates available for stage {stage}")
        bucket["embeddings"] = np.stack(bucket["embeddings"], axis=0).astype(np.float32)

    if not by_stage:
        raise RuntimeError(f"No retrieval candidates found for split '{retrieval_split}'")

    return by_stage


def retrieve_nearest(query_embedding: np.ndarray, stage_bank: Dict[str, object]) -> Dict[str, object]:
    bank = np.asarray(stage_bank["embeddings"], dtype=np.float32)
    scores = bank @ query_embedding
    best_idx = int(np.argmax(scores))
    record = dict(stage_bank["records"][best_idx])
    record["cosine"] = float(scores[best_idx])
    record["embedding"] = bank[best_idx]
    return record


def retrieve_topk(query_embedding: np.ndarray, stage_bank: Dict[str, object], top_k: int) -> List[Dict[str, object]]:
    bank = np.asarray(stage_bank["embeddings"], dtype=np.float32)
    scores = bank @ query_embedding
    k = max(1, min(int(top_k), int(scores.shape[0])))
    if k == scores.shape[0]:
        top_idx = np.argsort(scores)[::-1]
    else:
        top_idx = np.argpartition(scores, -k)[-k:]
        top_idx = top_idx[np.argsort(scores[top_idx])[::-1]]

    out: List[Dict[str, object]] = []
    for rank, idx in enumerate(top_idx, start=1):
        record = dict(stage_bank["records"][int(idx)])
        record["cosine"] = float(scores[int(idx)])
        record["embedding"] = bank[int(idx)]
        record["retrieval_rank"] = int(rank)
        out.append(record)
    return out


def retrieval_topk_for_stage(predicted_stage: int, retrieval_topk: int, early_retrieval_max_stage: int, early_retrieval_topk: int) -> int:
    if int(predicted_stage) <= int(early_retrieval_max_stage):
        return max(int(retrieval_topk), int(early_retrieval_topk))
    return int(retrieval_topk)


def retrieval_rerank_weights(
    predicted_stage: int,
    consistency_weight: float,
    anchor_weight: float,
    early_retrieval_max_stage: int,
    early_retrieval_consistency_multiplier: float,
    early_retrieval_anchor_multiplier: float,
    early_retrieval_source_weight: float,
) -> Tuple[float, float, float]:
    if int(predicted_stage) <= int(early_retrieval_max_stage):
        return (
            float(consistency_weight) * float(early_retrieval_consistency_multiplier),
            float(anchor_weight) * float(early_retrieval_anchor_multiplier),
            float(early_retrieval_source_weight),
        )
    return float(consistency_weight), float(anchor_weight), 0.0


def rerank_candidate(
    candidate: Dict[str, object],
    query_embedding: np.ndarray,
    source_embedding: np.ndarray,
    prev_retrieved_embedding: np.ndarray | None,
    anchor_embedding: np.ndarray,
    consistency_weight: float,
    anchor_weight: float,
    source_weight: float,
) -> Dict[str, object]:
    candidate_embedding = np.asarray(candidate["embedding"], dtype=np.float32)
    query_score = float(candidate_embedding @ query_embedding)
    source_score = float(candidate_embedding @ source_embedding)
    consistency_score = (
        float(candidate_embedding @ prev_retrieved_embedding)
        if prev_retrieved_embedding is not None
        else 0.0
    )
    anchor_score = float(candidate_embedding @ anchor_embedding)
    rerank_score = (
        query_score
        + float(source_weight) * source_score
        + float(consistency_weight) * consistency_score
        + float(anchor_weight) * anchor_score
    )

    out = dict(candidate)
    out["query_score"] = query_score
    out["source_score"] = source_score
    out["consistency_score"] = consistency_score
    out["anchor_score"] = anchor_score
    out["rerank_score"] = rerank_score
    return out


def build_contact_sheet(input_image: Path, rollout: List[Dict[str, object]], output_path: Path) -> None:
    tile_size = 256
    label_height = 28
    images: List[Image.Image] = []
    labels: List[str] = []

    with Image.open(input_image) as image:
        images.append(ImageOps.contain(image.convert("RGB"), (tile_size, tile_size)))
    labels.append("input")

    for step in rollout:
        image_path = (
            step.get("copied_image_path")
            or step.get("retrieved_image_path")
            or step.get("generated_image_path")
        )
        if not image_path:
            continue
        with Image.open(image_path) as image:
            images.append(ImageOps.contain(image.convert("RGB"), (tile_size, tile_size)))
        labels.append(f"stage {step['predicted_stage']}")

    sheet = Image.new("RGB", (tile_size * len(images), tile_size + label_height), color=(255, 255, 255))
    draw = ImageDraw.Draw(sheet)

    for idx, image in enumerate(images):
        x = idx * tile_size
        offset_x = x + (tile_size - image.width) // 2
        offset_y = (tile_size - image.height) // 2
        sheet.paste(image, (offset_x, offset_y))
        draw.text((x + 8, tile_size + 6), labels[idx], fill=(0, 0, 0))

    ensure_dir(output_path.parent)
    sheet.save(output_path)


def build_stage_chain(start_stage: int, end_stage: int, num_stages: int, stage_bank: Dict[int, Dict[str, object]]) -> List[int]:
    if start_stage < 0:
        raise ValueError("start-stage must be non-negative")
    if start_stage >= num_stages:
        raise ValueError(f"start-stage must be smaller than num_stages ({num_stages})")

    available = sorted(stage_bank.keys())
    if not available:
        raise RuntimeError("No stages available in retrieval bank")

    resolved_end = available[-1] if end_stage < 0 else end_stage
    if resolved_end >= num_stages:
        raise ValueError(f"end-stage must be smaller than num_stages ({num_stages})")

    if start_stage not in available:
        raise RuntimeError(f"start-stage {start_stage} is not available in retrieval bank {available}")
    if resolved_end not in available:
        raise RuntimeError(f"end-stage {resolved_end} is not available in retrieval bank {available}")

    start_pos = available.index(start_stage)
    end_pos = available.index(resolved_end)
    if start_pos >= end_pos:
        raise ValueError("start-stage must come before end-stage in the available stage sequence")

    return available[start_pos : end_pos + 1]


def rollout_stages(
    model: TransitionMLP,
    current_embedding: np.ndarray,
    anchor_embedding: np.ndarray,
    stage_bank: Dict[int, Dict[str, object]],
    stage_chain: List[int],
    output_dir: Path,
    device: torch.device,
    use_retrieved_embedding: bool,
    retrieval_topk: int,
    retrieval_beam_width: int,
    retrieval_consistency_weight: float,
    retrieval_anchor_weight: float,
    early_retrieval_max_stage: int,
    early_retrieval_topk: int,
    early_retrieval_consistency_multiplier: float,
    early_retrieval_anchor_multiplier: float,
    early_retrieval_source_weight: float,
) -> List[Dict[str, object]]:
    beam_width = max(1, int(retrieval_beam_width))
    beam: List[Dict[str, object]] = [
        {
            "model_embedding": np.asarray(current_embedding, dtype=np.float32),
            "prev_retrieved_embedding": None,
            "score": 0.0,
            "steps": [],
        }
    ]

    for src_stage, predicted_stage in zip(stage_chain[:-1], stage_chain[1:]):
        stage_topk = retrieval_topk_for_stage(
            predicted_stage,
            retrieval_topk,
            early_retrieval_max_stage,
            early_retrieval_topk,
        )
        stage_consistency_weight, stage_anchor_weight, stage_source_weight = retrieval_rerank_weights(
            predicted_stage,
            retrieval_consistency_weight,
            retrieval_anchor_weight,
            early_retrieval_max_stage,
            early_retrieval_consistency_multiplier,
            early_retrieval_anchor_multiplier,
            early_retrieval_source_weight,
        )
        next_beam: List[Dict[str, object]] = []

        for state in beam:
            source_embedding = np.asarray(state["model_embedding"], dtype=np.float32)
            src_tensor = torch.from_numpy(source_embedding).unsqueeze(0).to(device)
            src_stage_tensor = torch.tensor([src_stage], dtype=torch.long, device=device)

            with torch.no_grad():
                pred = model(src_tensor, src_stage_tensor)[0].detach().cpu().numpy().astype(np.float32)

            pred /= max(float(np.linalg.norm(pred)), 1e-12)
            candidates = retrieve_topk(pred, stage_bank[predicted_stage], stage_topk)
            if not candidates:
                raise RuntimeError(f"No retrieval candidates available for stage {predicted_stage}")

            scored = [
                rerank_candidate(
                    candidate=candidate,
                    query_embedding=pred,
                    source_embedding=source_embedding,
                    prev_retrieved_embedding=state["prev_retrieved_embedding"],
                    anchor_embedding=anchor_embedding,
                    consistency_weight=stage_consistency_weight,
                    anchor_weight=stage_anchor_weight,
                    source_weight=stage_source_weight,
                )
                for candidate in candidates
            ]
            scored.sort(key=lambda item: float(item["rerank_score"]), reverse=True)

            for candidate in scored[:beam_width]:
                next_embedding = np.asarray(candidate["embedding"] if use_retrieved_embedding else pred, dtype=np.float32)
                step = {
                    "source_stage": src_stage,
                    "predicted_stage": predicted_stage,
                    "retrieved_frame_key": candidate["frame_key"],
                    "retrieved_stem": candidate["stem"],
                    "retrieved_split": candidate["split"],
                    "retrieved_image_path": str(candidate["image_path"]),
                    "retrieval_rank": int(candidate["retrieval_rank"]),
                    "retrieval_cosine": float(candidate["cosine"]),
                    "query_score": float(candidate["query_score"]),
                    "source_score": float(candidate["source_score"]),
                    "consistency_score": float(candidate["consistency_score"]),
                    "anchor_score": float(candidate["anchor_score"]),
                    "rerank_score": float(candidate["rerank_score"]),
                    "rerank_topk": int(stage_topk),
                    "rerank_consistency_weight": float(stage_consistency_weight),
                    "rerank_anchor_weight": float(stage_anchor_weight),
                    "rerank_source_weight": float(stage_source_weight),
                }
                next_beam.append(
                    {
                        "model_embedding": next_embedding,
                        "prev_retrieved_embedding": np.asarray(candidate["embedding"], dtype=np.float32),
                        "score": float(state["score"]) + float(candidate["rerank_score"]),
                        "steps": [*state["steps"], step],
                    }
                )

        if not next_beam:
            raise RuntimeError(f"Rollout beam collapsed at stage {predicted_stage}")
        next_beam.sort(key=lambda item: float(item["score"]), reverse=True)
        beam = next_beam[:beam_width]

    best_steps = list(beam[0]["steps"])
    rollout: List[Dict[str, object]] = []
    for step in best_steps:
        retrieved_path = Path(step["retrieved_image_path"])
        require_file(retrieved_path, "Retrieved image")
        copied_name = f"stage_{int(step['predicted_stage']):02d}_{step['retrieved_frame_key']}{retrieved_path.suffix}"
        copied_path = output_dir / copied_name
        shutil.copy2(retrieved_path, copied_path)
        step_out = dict(step)
        step_out["copied_image_path"] = str(copied_path)
        rollout.append(step_out)

    return rollout


def load_pixel_decoder(checkpoint_path: Path, device: torch.device) -> Tuple[PixelDecoderUNet, Dict[str, object]]:
    require_file(checkpoint_path, "Pixel decoder checkpoint")
    checkpoint = torch.load(checkpoint_path, map_location=device)
    if not isinstance(checkpoint, dict) or "model_config" not in checkpoint:
        raise RuntimeError(f"Pixel decoder checkpoint is missing model_config: {checkpoint_path}")

    config = dict(checkpoint["model_config"])
    model = PixelDecoderUNet(
        embedding_dim=int(config["embedding_dim"]),
        num_stages=int(config["num_stages"]),
        base_channels=int(config.get("base_channels", 32)),
        stage_embed_dim=int(config.get("stage_embed_dim", 16)),
        cond_dim=int(config.get("cond_dim", 256)),
        output_mode=str(config.get("output_mode", "direct")),
        residual_scale=float(config.get("residual_scale", 1.0)),
    ).to(device)

    state = checkpoint.get("model_state_dict", checkpoint)
    model.load_state_dict(state)
    model.eval()
    return model, config


def load_structural_decoder(checkpoint_path: Path, device: torch.device) -> Tuple[StructuralLayerUNet, Dict[str, object]]:
    require_file(checkpoint_path, "Structural decoder checkpoint")
    checkpoint = torch.load(checkpoint_path, map_location=device)
    if not isinstance(checkpoint, dict) or "model_config" not in checkpoint:
        raise RuntimeError(f"Structural decoder checkpoint is missing model_config: {checkpoint_path}")

    config = dict(checkpoint["model_config"])
    model = StructuralLayerUNet(
        num_stages=int(config["num_stages"]),
        base_channels=int(config.get("base_channels", 32)),
        stage_embed_dim=int(config.get("stage_embed_dim", 16)),
        cond_dim=int(config.get("cond_dim", 128)),
    ).to(device)

    state = checkpoint.get("model_state_dict", checkpoint)
    model.load_state_dict(state)
    model.eval()
    return model, config


def rollout_stages_with_pixel_decoder(
    model: TransitionMLP,
    pixel_decoder: PixelDecoderUNet,
    structural_decoder: StructuralLayerUNet | None,
    current_embedding: np.ndarray,
    anchor_embedding: np.ndarray,
    input_image: Path,
    stage_bank: Dict[int, Dict[str, object]],
    start_stage: int,
    end_stage: int,
    output_dir: Path,
    device: torch.device,
    image_size: int,
    save_retrieval_fallback: bool,
    use_retrieved_embedding: bool,
    structural_until_stage: int,
    structural_threshold: float,
    retrieval_topk: int,
    retrieval_consistency_weight: float,
    retrieval_anchor_weight: float,
    early_retrieval_max_stage: int,
    early_retrieval_topk: int,
    early_retrieval_consistency_multiplier: float,
    early_retrieval_anchor_multiplier: float,
    early_retrieval_source_weight: float,
) -> List[Dict[str, object]]:
    rollout: List[Dict[str, object]] = []
    prev_retrieved_embedding: np.ndarray | None = None

    with Image.open(input_image) as image:
        current_image = image_to_tensor(image, image_size).to(device)

    for src_stage in range(start_stage, end_stage):
        src_tensor = torch.from_numpy(current_embedding).unsqueeze(0).to(device)
        src_stage_tensor = torch.tensor([src_stage], dtype=torch.long, device=device)
        predicted_stage = src_stage + 1

        with torch.no_grad():
            pred = model(src_tensor, src_stage_tensor)
            pred_np = pred[0].detach().cpu().numpy().astype(np.float32)
            pred_np /= max(float(np.linalg.norm(pred_np)), 1e-12)
            if structural_decoder is not None and predicted_stage <= structural_until_stage:
                layer_probs = torch.sigmoid(structural_decoder(current_image.unsqueeze(0), src_stage_tensor))
                layer = (layer_probs >= structural_threshold).to(dtype=torch.float32)
                generated = compose_white_layer(current_image.unsqueeze(0), layer)[0]
                layer_path = output_dir / f"stage_{predicted_stage:02d}_structural_layer.png"
                tensor_to_pil(layer[0].repeat(3, 1, 1)).save(layer_path)
                generator_name = "structural"
            else:
                generated = pixel_decoder(current_image.unsqueeze(0), pred, src_stage_tensor)[0]
                layer_path = None
                generator_name = "dense_pixel"

        generated_path = output_dir / f"stage_{predicted_stage:02d}_generated.png"
        tensor_to_pil(generated).save(generated_path)

        step: Dict[str, object] = {
            "source_stage": src_stage,
            "predicted_stage": predicted_stage,
            "generator": generator_name,
            "generated_image_path": str(generated_path),
        }
        if layer_path is not None:
            step["generated_layer_path"] = str(layer_path)

        match = None
        if save_retrieval_fallback or use_retrieved_embedding:
            stage_topk = retrieval_topk_for_stage(
                predicted_stage,
                retrieval_topk,
                early_retrieval_max_stage,
                early_retrieval_topk,
            )
            stage_consistency_weight, stage_anchor_weight, stage_source_weight = retrieval_rerank_weights(
                predicted_stage,
                retrieval_consistency_weight,
                retrieval_anchor_weight,
                early_retrieval_max_stage,
                early_retrieval_consistency_multiplier,
                early_retrieval_anchor_multiplier,
                early_retrieval_source_weight,
            )
            candidates = retrieve_topk(pred_np, stage_bank[predicted_stage], stage_topk)
            if not candidates:
                raise RuntimeError(f"No retrieval candidates available for stage {predicted_stage}")
            scored = [
                rerank_candidate(
                    candidate=candidate,
                    query_embedding=pred_np,
                    source_embedding=current_embedding,
                    prev_retrieved_embedding=prev_retrieved_embedding,
                    anchor_embedding=anchor_embedding,
                    consistency_weight=stage_consistency_weight,
                    anchor_weight=stage_anchor_weight,
                    source_weight=stage_source_weight,
                )
                for candidate in candidates
            ]
            scored.sort(key=lambda item: float(item["rerank_score"]), reverse=True)
            match = scored[0]
            step.update(
                {
                    "retrieved_frame_key": match["frame_key"],
                    "retrieved_stem": match["stem"],
                    "retrieved_split": match["split"],
                    "retrieval_rank": int(match["retrieval_rank"]),
                    "retrieval_cosine": float(match["cosine"]),
                    "query_score": float(match["query_score"]),
                    "source_score": float(match["source_score"]),
                    "consistency_score": float(match["consistency_score"]),
                    "anchor_score": float(match["anchor_score"]),
                    "rerank_score": float(match["rerank_score"]),
                    "rerank_topk": int(stage_topk),
                    "rerank_consistency_weight": float(stage_consistency_weight),
                    "rerank_anchor_weight": float(stage_anchor_weight),
                    "rerank_source_weight": float(stage_source_weight),
                }
            )
            if save_retrieval_fallback:
                retrieved_path = Path(match["image_path"])
                require_file(retrieved_path, "Retrieved image")
                copied_name = f"stage_{predicted_stage:02d}_retrieval_{match['frame_key']}{retrieved_path.suffix}"
                copied_path = output_dir / copied_name
                shutil.copy2(retrieved_path, copied_path)
                step.update(
                    {
                        "retrieved_image_path": str(retrieved_path),
                        "copied_image_path": str(copied_path),
                    }
                )

        rollout.append(step)
        current_embedding = np.asarray(match["embedding"] if use_retrieved_embedding and match is not None else pred_np, dtype=np.float32)
        prev_retrieved_embedding = np.asarray(match["embedding"], dtype=np.float32) if match is not None else prev_retrieved_embedding
        current_image = generated.detach()

    return rollout


def main() -> None:
    args = parse_args()
    input_image = Path(args.input_image)
    output_dir = Path(args.output_dir)
    ensure_dir(output_dir)
    device = torch.device(args.device)

    model_config = load_model_config(Path(args.metrics_json))
    checkpoint = Path(args.checkpoint)
    embeddings_path = Path(args.embeddings_npz)
    embedding_backend = resolve_embedding_backend(args.embedding_backend, model_config, embeddings_path)
    model_id = resolve_model_id(args.model_id, embedding_backend, model_config)

    stage_bank = load_frame_bank(embeddings_path, Path(args.manifest_frames), args.retrieval_split)
    stage_chain = build_stage_chain(args.start_stage, args.end_stage, int(model_config["num_stages"]), stage_bank)

    embedding_dim = int(np.asarray(next(iter(stage_bank.values()))["embeddings"]).shape[1])
    model = TransitionMLP(
        embedding_dim=embedding_dim,
        hidden_dim=int(model_config["hidden_dim"]),
        stage_embed_dim=int(model_config["stage_embed_dim"]),
        dropout=float(model_config["dropout"]),
        num_stages=int(model_config["num_stages"]),
    ).to(device)

    load_transition_mlp_checkpoint(model, checkpoint, device)
    model.eval()

    if embedding_backend == "dino":
        current_embedding = embed_image_with_dino(input_image, model_id, device)
    else:
        current_embedding = embed_image_with_clip(input_image, model_id, device)
    anchor_embedding = np.asarray(current_embedding, dtype=np.float32).copy()
    structural_threshold = 0.5

    if args.render_mode == "retrieval":
        rollout = rollout_stages(
            model=model,
            current_embedding=current_embedding,
            anchor_embedding=anchor_embedding,
            stage_bank=stage_bank,
            stage_chain=stage_chain,
            output_dir=output_dir,
            device=device,
            use_retrieved_embedding=args.use_retrieved_embedding,
            retrieval_topk=args.retrieval_topk,
            retrieval_beam_width=args.retrieval_beam_width,
            retrieval_consistency_weight=args.retrieval_consistency_weight,
            retrieval_anchor_weight=args.retrieval_anchor_weight,
            early_retrieval_max_stage=args.early_retrieval_max_stage,
            early_retrieval_topk=args.early_retrieval_topk,
            early_retrieval_consistency_multiplier=args.early_retrieval_consistency_multiplier,
            early_retrieval_anchor_multiplier=args.early_retrieval_anchor_multiplier,
            early_retrieval_source_weight=args.early_retrieval_source_weight,
        )
    else:
        pixel_decoder, pixel_config = load_pixel_decoder(Path(args.pixel_decoder_checkpoint), device)
        image_size = int(pixel_config.get("image_size", 256))
        structural_decoder = None
        if not args.disable_structural_decoder:
            structural_decoder, structural_config = load_structural_decoder(Path(args.structural_decoder_checkpoint), device)
            structural_image_size = int(structural_config.get("image_size", image_size))
            if structural_image_size != image_size:
                raise RuntimeError(
                    "Pixel and structural decoder checkpoints disagree on image_size: "
                    f"{image_size} vs {structural_image_size}"
                )
            structural_threshold = (
                float(args.structural_threshold)
                if args.structural_threshold is not None
                else float(structural_config.get("threshold", 0.5))
            )
        elif args.structural_threshold is not None:
            structural_threshold = float(args.structural_threshold)

        rollout = rollout_stages_with_pixel_decoder(
            model=model,
            pixel_decoder=pixel_decoder,
            structural_decoder=structural_decoder,
            current_embedding=current_embedding,
            anchor_embedding=anchor_embedding,
            input_image=input_image,
            stage_bank=stage_bank,
            start_stage=stage_chain[0],
            end_stage=stage_chain[-1],
            output_dir=output_dir,
            device=device,
            image_size=image_size,
            save_retrieval_fallback=args.save_retrieval_fallback,
            use_retrieved_embedding=args.use_retrieved_embedding,
            structural_until_stage=args.structural_until_stage,
            structural_threshold=structural_threshold,
            retrieval_topk=args.retrieval_topk,
            retrieval_consistency_weight=args.retrieval_consistency_weight,
            retrieval_anchor_weight=args.retrieval_anchor_weight,
            early_retrieval_max_stage=args.early_retrieval_max_stage,
            early_retrieval_topk=args.early_retrieval_topk,
            early_retrieval_consistency_multiplier=args.early_retrieval_consistency_multiplier,
            early_retrieval_anchor_multiplier=args.early_retrieval_anchor_multiplier,
            early_retrieval_source_weight=args.early_retrieval_source_weight,
        )

    resolved_end_stage = stage_chain[-1]

    summary = {
        "input_image": str(input_image),
        "checkpoint": str(checkpoint),
        "embedding_backend": embedding_backend,
        "model_id": model_id,
        "device": str(device),
        "render_mode": args.render_mode,
        "start_stage": args.start_stage,
        "end_stage": resolved_end_stage,
        "stage_chain": stage_chain,
        "retrieval_split": args.retrieval_split,
        "retrieval_topk": args.retrieval_topk,
        "retrieval_beam_width": args.retrieval_beam_width,
        "retrieval_consistency_weight": args.retrieval_consistency_weight,
        "retrieval_anchor_weight": args.retrieval_anchor_weight,
        "early_retrieval_max_stage": args.early_retrieval_max_stage,
        "early_retrieval_topk": args.early_retrieval_topk,
        "early_retrieval_consistency_multiplier": args.early_retrieval_consistency_multiplier,
        "early_retrieval_anchor_multiplier": args.early_retrieval_anchor_multiplier,
        "early_retrieval_source_weight": args.early_retrieval_source_weight,
        "save_retrieval_fallback": bool(args.save_retrieval_fallback),
        "structural_until_stage": int(args.structural_until_stage),
        "structural_threshold": float(structural_threshold),
        "use_retrieved_embedding": bool(args.use_retrieved_embedding),
        "rollout": rollout,
    }

    write_json(output_dir / "rollout_summary.json", summary)

    build_contact_sheet(input_image, rollout, output_dir / "rollout_contact_sheet.png")

    print("Transition rollout complete")
    print(f"Input:        {input_image}")
    print(f"Stages:       {stage_chain[0]} -> {stage_chain[-1]} (chain: {stage_chain})")
    print(f"Steps:        {len(rollout)}")
    print(f"Output dir:   {output_dir}")


if __name__ == "__main__":
    main()
