import argparse
import shutil
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import torch
from PIL import Image, ImageDraw, ImageOps

from learning_utils import (
    TransitionMLP,
    default_device,
    embed_image_with_clip,
    load_checkpoint_state,
    load_embedding_archive,
    load_model_config,
)
from script_utils import LEARNING_ROOT, ensure_dir, read_csv_rows, require_file, write_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Roll a rough owl sketch forward through latent stages.")
    parser.add_argument("input_image", help="Path to a rough sketch image")
    parser.add_argument(
        "--checkpoint",
        default=str(LEARNING_ROOT / "ar_baseline" / "best_model.pt"),
        help="Path to trained transition baseline checkpoint",
    )
    parser.add_argument(
        "--metrics-json",
        default=str(LEARNING_ROOT / "ar_baseline" / "metrics.json"),
        help="Metrics JSON written by train_transition_baseline.py",
    )
    parser.add_argument(
        "--embeddings-npz",
        default=str(LEARNING_ROOT / "embeddings" / "clip_embeddings_all.npz"),
        help="Path to embedding .npz generated by extract_clip_embeddings.py",
    )
    parser.add_argument(
        "--manifest-frames",
        default=str(LEARNING_ROOT / "manifest_frames.csv"),
        help="Path to frame manifest CSV from build_manifest.py",
    )
    parser.add_argument(
        "--output-dir",
        default=str(LEARNING_ROOT / "inference"),
        help="Output directory for rollout artifacts",
    )
    parser.add_argument("--model-id", default="openai/clip-vit-base-patch32", help="Hugging Face CLIP model id")
    parser.add_argument("--device", default=default_device(), help="Inference device")
    parser.add_argument("--start-stage", type=int, default=0, help="Stage index represented by the input sketch")
    parser.add_argument("--end-stage", type=int, default=9, help="Final stage index to roll out to")
    parser.add_argument(
        "--retrieval-split",
        choices=["train", "val", "test", "all"],
        default="train",
        help="Which split to retrieve nearest stage images from",
    )
    parser.add_argument(
        "--use-retrieved-embedding",
        action="store_true",
        help="Snap each step to the retrieved embedding before predicting the next stage",
    )
    return parser.parse_args()


def load_frame_bank(npz_path: Path, manifest_path: Path, retrieval_split: str) -> Dict[int, Dict[str, object]]:
    data = load_embedding_archive(npz_path, normalize=True)
    embeddings = data["embeddings"]
    stems = data["stems"]
    stage_indices = data["stage_indices"]
    image_paths = data["image_paths"]
    splits = data["splits"]

    manifest_lookup = {
        (str(row["stem"]), int(row["stage_idx"])): row
        for row in read_csv_rows(manifest_path, description="Frame manifest")
    }

    by_stage: Dict[int, Dict[str, object]] = {}
    for stem, stage_idx, image_path, split, emb in zip(stems, stage_indices, image_paths, splits, embeddings):
        stage = int(stage_idx)
        split_name = str(split)
        if retrieval_split != "all" and split_name != retrieval_split:
            continue

        meta = manifest_lookup.get((str(stem), stage), {})
        stage_bucket = by_stage.setdefault(stage, {"embeddings": [], "records": []})
        stage_bucket["embeddings"].append(emb)
        stage_bucket["records"].append(
            {
                "stem": str(stem),
                "stage_idx": stage,
                "split": split_name,
                "image_path": str(image_path),
                "frame_key": meta.get("frame_key", f"{stem}_stage{stage:02d}"),
            }
        )

    for stage, bucket in by_stage.items():
        if len(bucket["embeddings"]) == 0:
            raise RuntimeError(f"No retrieval candidates available for stage {stage}")
        bucket["embeddings"] = np.stack(bucket["embeddings"], axis=0).astype(np.float32)

    if not by_stage:
        raise RuntimeError(f"No retrieval candidates found for split '{retrieval_split}'")

    return by_stage


def retrieve_nearest(query_embedding: np.ndarray, stage_bank: Dict[str, object]) -> Dict[str, object]:
    bank = np.asarray(stage_bank["embeddings"], dtype=np.float32)
    scores = bank @ query_embedding
    best_idx = int(np.argmax(scores))
    record = dict(stage_bank["records"][best_idx])
    record["cosine"] = float(scores[best_idx])
    record["embedding"] = bank[best_idx]
    return record


def build_contact_sheet(input_image: Path, rollout: List[Dict[str, object]], output_path: Path) -> None:
    tile_size = 256
    label_height = 28
    images: List[Image.Image] = []
    labels: List[str] = []

    with Image.open(input_image) as image:
        images.append(ImageOps.contain(image.convert("RGB"), (tile_size, tile_size)))
    labels.append("input")

    for step in rollout:
        with Image.open(step["retrieved_image_path"]) as image:
            images.append(ImageOps.contain(image.convert("RGB"), (tile_size, tile_size)))
        labels.append(f"stage {step['predicted_stage']}")

    sheet = Image.new("RGB", (tile_size * len(images), tile_size + label_height), color=(255, 255, 255))
    draw = ImageDraw.Draw(sheet)

    for idx, image in enumerate(images):
        x = idx * tile_size
        offset_x = x + (tile_size - image.width) // 2
        offset_y = (tile_size - image.height) // 2
        sheet.paste(image, (offset_x, offset_y))
        draw.text((x + 8, tile_size + 6), labels[idx], fill=(0, 0, 0))

    ensure_dir(output_path.parent)
    sheet.save(output_path)


def validate_stage_range(start_stage: int, end_stage: int, num_stages: int, stage_bank: Dict[int, Dict[str, object]]) -> None:
    if start_stage >= end_stage:
        raise ValueError("start-stage must be smaller than end-stage")
    if start_stage < 0:
        raise ValueError("start-stage must be non-negative")
    if end_stage >= num_stages:
        raise ValueError(f"end-stage must be smaller than num_stages ({num_stages})")

    missing = [stage for stage in range(start_stage + 1, end_stage + 1) if stage not in stage_bank]
    if missing:
        raise RuntimeError(f"No retrieval bank available for stages: {missing}")


def rollout_stages(
    model: TransitionMLP,
    current_embedding: np.ndarray,
    stage_bank: Dict[int, Dict[str, object]],
    start_stage: int,
    end_stage: int,
    output_dir: Path,
    device: torch.device,
    use_retrieved_embedding: bool,
) -> List[Dict[str, object]]:
    rollout: List[Dict[str, object]] = []

    for src_stage in range(start_stage, end_stage):
        src_tensor = torch.from_numpy(current_embedding).unsqueeze(0).to(device)
        src_stage_tensor = torch.tensor([src_stage], dtype=torch.long, device=device)

        with torch.no_grad():
            pred = model(src_tensor, src_stage_tensor)[0].detach().cpu().numpy().astype(np.float32)

        pred /= max(float(np.linalg.norm(pred)), 1e-12)
        predicted_stage = src_stage + 1

        match = retrieve_nearest(pred, stage_bank[predicted_stage])
        retrieved_path = Path(match["image_path"])
        require_file(retrieved_path, "Retrieved image")

        copied_name = f"stage_{predicted_stage:02d}_{match['frame_key']}{retrieved_path.suffix}"
        copied_path = output_dir / copied_name
        shutil.copy2(retrieved_path, copied_path)

        rollout.append(
            {
                "source_stage": src_stage,
                "predicted_stage": predicted_stage,
                "retrieved_frame_key": match["frame_key"],
                "retrieved_stem": match["stem"],
                "retrieved_split": match["split"],
                "retrieved_image_path": str(retrieved_path),
                "copied_image_path": str(copied_path),
                "retrieval_cosine": float(match["cosine"]),
            }
        )

        current_embedding = np.asarray(match["embedding"] if use_retrieved_embedding else pred, dtype=np.float32)

    return rollout


def main() -> None:
    args = parse_args()
    input_image = Path(args.input_image)
    output_dir = Path(args.output_dir)
    ensure_dir(output_dir)
    device = torch.device(args.device)

    model_config = load_model_config(Path(args.metrics_json))
    checkpoint = Path(args.checkpoint)

    stage_bank = load_frame_bank(Path(args.embeddings_npz), Path(args.manifest_frames), args.retrieval_split)
    validate_stage_range(args.start_stage, args.end_stage, int(model_config["num_stages"]), stage_bank)

    embedding_dim = int(np.asarray(next(iter(stage_bank.values()))["embeddings"]).shape[1])
    model = TransitionMLP(
        embedding_dim=embedding_dim,
        hidden_dim=int(model_config["hidden_dim"]),
        stage_embed_dim=int(model_config["stage_embed_dim"]),
        dropout=float(model_config["dropout"]),
        num_stages=int(model_config["num_stages"]),
    ).to(device)

    state_dict = load_checkpoint_state(checkpoint, device)
    model.load_state_dict(state_dict)
    model.eval()

    current_embedding = embed_image_with_clip(input_image, args.model_id, device)
    rollout = rollout_stages(
        model=model,
        current_embedding=current_embedding,
        stage_bank=stage_bank,
        start_stage=args.start_stage,
        end_stage=args.end_stage,
        output_dir=output_dir,
        device=device,
        use_retrieved_embedding=args.use_retrieved_embedding,
    )

    summary = {
        "input_image": str(input_image),
        "checkpoint": str(checkpoint),
        "model_id": args.model_id,
        "device": str(device),
        "start_stage": args.start_stage,
        "end_stage": args.end_stage,
        "retrieval_split": args.retrieval_split,
        "use_retrieved_embedding": bool(args.use_retrieved_embedding),
        "rollout": rollout,
    }

    write_json(output_dir / "rollout_summary.json", summary)

    build_contact_sheet(input_image, rollout, output_dir / "rollout_contact_sheet.png")

    print("Transition rollout complete")
    print(f"Input:        {input_image}")
    print(f"Stages:       {args.start_stage} -> {args.end_stage}")
    print(f"Steps:        {len(rollout)}")
    print(f"Output dir:   {output_dir}")


if __name__ == "__main__":
    main()
