import argparse
from pathlib import Path

import numpy as np
import torch

from learning_utils import TransitionSequenceCNN, default_device
from train_transition_transformer_contrastive import (
    PrefixTransitionDataset,
    build_eval_artifacts,
    build_prefix_examples,
    collate_prefix_batch,
    evaluate,
    fit_pca_transform,
    fit_standardization,
    load_combined_embedding_lookup,
    load_frame_rows,
    make_lr_scheduler,
    metric_value,
    set_seed,
    split_rows,
    train_one_epoch,
    transform_rows_pca,
    transform_rows_standardize,
)
from script_utils import LEARNING_ROOT, ensure_dir, write_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a temporal CNN next-stage predictor on stage trajectories with contrastive learning."
    )
    parser.add_argument(
        "--embeddings-npz",
        default=str(LEARNING_ROOT / "embeddings" / "dino_embeddings_all.npz"),
        help="Path to embedding .npz generated by the embedding extraction scripts",
    )
    parser.add_argument(
        "--aux-embeddings-npz",
        nargs="*",
        default=[],
        help="Optional additional embedding archives to concatenate with the primary archive",
    )
    parser.add_argument(
        "--embedding-key-alignment",
        choices=["intersection", "strict"],
        default="intersection",
        help="How to align multiple embedding archives when their (stem, stage_idx) coverage differs",
    )
    parser.add_argument(
        "--manifest-frames",
        default=str(LEARNING_ROOT / "manifest_frames.csv"),
        help="Path to frame manifest CSV from build_manifest.py",
    )
    parser.add_argument(
        "--output-dir",
        default=str(LEARNING_ROOT / "transition_cnn_contrastive"),
        help="Output directory for training artifacts",
    )
    parser.add_argument("--device", default=default_device(), help="Training device")
    parser.add_argument("--batch-size", type=int, default=64, help="Mini-batch size")
    parser.add_argument("--epochs", type=int, default=250, help="Maximum number of epochs")
    parser.add_argument("--lr", type=float, default=3e-4, help="Learning rate")
    parser.add_argument("--min-lr", type=float, default=1e-5, help="Minimum LR for cosine annealing")
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="AdamW weight decay")
    parser.add_argument(
        "--feature-transform",
        choices=["auto", "none", "standardize", "pca", "pca_whiten"],
        default="auto",
        help="Optional train-split feature transform applied before row normalization",
    )
    parser.add_argument(
        "--feature-output-dim",
        type=int,
        default=256,
        help="Output dimension for PCA-based feature transforms (ignored otherwise)",
    )
    parser.add_argument(
        "--context-window",
        type=int,
        default=3,
        help="Use only the most recent K source stages in each prefix (0 keeps the full prefix)",
    )
    parser.add_argument("--model-dim", type=int, default=256, help="CNN hidden width")
    parser.add_argument("--num-layers", type=int, default=4, help="Number of temporal residual blocks")
    parser.add_argument("--cnn-kernel-size", type=int, default=3, help="Temporal kernel size for the CNN sequence model.")
    parser.add_argument(
        "--cnn-dilation-cycle",
        type=int,
        default=3,
        help="Number of dilation steps before the CNN sequence model repeats its dilation pattern.",
    )
    parser.add_argument("--stage-embed-dim", type=int, default=32, help="Stage embedding size before projection")
    parser.add_argument("--dropout", type=float, default=0.1, help="Dropout in the CNN model")
    parser.add_argument(
        "--source-feature-dropout",
        type=float,
        default=0.0,
        help="Dropout applied to source embedding features during training",
    )
    parser.add_argument(
        "--source-noise-std",
        type=float,
        default=0.0,
        help="Gaussian noise std added to source embeddings during training before renormalization",
    )
    parser.add_argument(
        "--disable-stage-specific-output-heads",
        action="store_true",
        help="Use shared output heads instead of source-stage-specific output heads",
    )
    parser.add_argument(
        "--stage-head-mode",
        choices=["auto", "shared", "stage-specific"],
        default="auto",
        help="Whether to use shared or source-stage-specific output heads",
    )
    parser.add_argument("--grad-clip-norm", type=float, default=1.0, help="Gradient clipping norm; <= 0 disables clipping")
    parser.add_argument("--cosine-weight", type=float, default=0.25, help="Weight for cosine regression loss")
    parser.add_argument("--contrastive-weight", type=float, default=1.0, help="Weight for InfoNCE retrieval loss")
    parser.add_argument(
        "--margin-loss-weight",
        type=float,
        default=0.0,
        help="Weight for a same-stage hard-negative margin loss that sharpens retrieval@1",
    )
    parser.add_argument(
        "--margin-loss-value",
        type=float,
        default=0.04,
        help="Required margin between the correct target and the hardest same-stage negative",
    )
    parser.add_argument("--temperature", type=float, default=0.07, help="Temperature for contrastive retrieval loss")
    parser.add_argument(
        "--selection-metric",
        choices=["retrieval_at_1", "cosine", "blended"],
        default="retrieval_at_1",
        help="Validation metric used for checkpoint selection and early stopping",
    )
    parser.add_argument("--blend-retrieval-weight", type=float, default=0.85, help="Retrieval weight in blended checkpoint selection")
    parser.add_argument("--blend-cosine-weight", type=float, default=0.15, help="Cosine weight in blended checkpoint selection")
    parser.add_argument("--patience", type=int, default=30, help="Early stopping patience on the selected validation metric")
    parser.add_argument("--lr-warmup-epochs", type=int, default=10, help="Number of warmup epochs before cosine annealing")
    parser.add_argument("--num-workers", type=int, default=0, help="DataLoader worker count")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    return parser.parse_args()


def resolve_feature_transform(mode: str, embeddings_path: Path) -> str:
    if mode != "auto":
        return mode
    return "standardize" if "dino" in embeddings_path.name.lower() else "none"


def resolve_stage_head_mode(mode: str, disable_stage_specific_output_heads: bool, embeddings_path: Path) -> str:
    if disable_stage_specific_output_heads:
        return "shared"
    if mode != "auto":
        return mode
    return "shared" if "dino" in embeddings_path.name.lower() else "stage-specific"


def main() -> None:
    args = parse_args()
    set_seed(args.seed)

    embeddings_path = Path(args.embeddings_npz)
    aux_embedding_paths = [Path(path) for path in args.aux_embeddings_npz]
    embedding_paths = [embeddings_path, *aux_embedding_paths]
    output_dir = Path(args.output_dir)
    ensure_dir(output_dir)
    device = torch.device(args.device)

    lookup, embedding_dim, embedding_alignment = load_combined_embedding_lookup(
        embedding_paths,
        alignment=args.embedding_key_alignment,
    )
    frame_rows = load_frame_rows(Path(args.manifest_frames), lookup)
    examples, skipped_noncontiguous = build_prefix_examples(frame_rows, args.context_window)
    splits = split_rows(examples)
    feature_transform = resolve_feature_transform(args.feature_transform, embeddings_path)
    stage_head_mode = resolve_stage_head_mode(args.stage_head_mode, args.disable_stage_specific_output_heads, embeddings_path)

    if feature_transform == "standardize":
        feature_mean, feature_std = fit_standardization(splits["train"])
        splits = {name: transform_rows_standardize(rows, feature_mean, feature_std) for name, rows in splits.items()}
        feature_components = None
        feature_scales = None
        transformed_embedding_dim = embedding_dim
    elif feature_transform in {"pca", "pca_whiten"}:
        pca_transform = fit_pca_transform(
            splits["train"],
            output_dim=args.feature_output_dim,
            whiten=(feature_transform == "pca_whiten"),
        )
        feature_mean = np.asarray(pca_transform["mean"], dtype=np.float32)
        feature_components = np.asarray(pca_transform["components"], dtype=np.float32)
        feature_scales = np.asarray(pca_transform["scales"], dtype=np.float32)
        feature_std = None
        transformed_embedding_dim = int(pca_transform["output_dim"])
        splits = {
            name: transform_rows_pca(rows, feature_mean, feature_components, feature_scales)
            for name, rows in splits.items()
        }
        np.savez_compressed(
            output_dir / "feature_transform.npz",
            mean=feature_mean,
            components=feature_components,
            scales=feature_scales,
            output_dim=np.array([transformed_embedding_dim], dtype=np.int32),
            whiten=np.array([1 if feature_transform == "pca_whiten" else 0], dtype=np.int8),
        )
    else:
        feature_mean = None
        feature_std = None
        feature_components = None
        feature_scales = None
        transformed_embedding_dim = embedding_dim

    max_stage_idx = max(int(row["tgt_stage_idx"]) for row in examples)
    max_seq_len = max(int(np.asarray(row["src_stage_indices"]).shape[0]) for row in examples)

    datasets = {
        "train": PrefixTransitionDataset(splits["train"]),
        "val": PrefixTransitionDataset(splits["val"]),
        "test": PrefixTransitionDataset(splits["test"]),
    }
    pin_memory = device.type == "cuda"
    loaders = {
        "train": torch.utils.data.DataLoader(
            datasets["train"],
            batch_size=args.batch_size,
            shuffle=True,
            num_workers=args.num_workers,
            pin_memory=pin_memory,
            collate_fn=collate_prefix_batch,
        ),
        "val": torch.utils.data.DataLoader(
            datasets["val"],
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=pin_memory,
            collate_fn=collate_prefix_batch,
        ),
        "test": torch.utils.data.DataLoader(
            datasets["test"],
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=pin_memory,
            collate_fn=collate_prefix_batch,
        ),
    }

    model = TransitionSequenceCNN(
        embedding_dim=transformed_embedding_dim,
        model_dim=args.model_dim,
        num_layers=args.num_layers,
        kernel_size=args.cnn_kernel_size,
        dilation_cycle=args.cnn_dilation_cycle,
        dropout=args.dropout,
        num_stages=max_stage_idx + 1,
        max_seq_len=max_seq_len,
        stage_embed_dim=args.stage_embed_dim,
        stage_specific_output_heads=(stage_head_mode == "stage-specific"),
    ).to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    scheduler = make_lr_scheduler(optimizer, args)
    best_state = None
    best_val_score = -float("inf")
    epochs_without_improvement = 0
    history = []

    val_centroids, val_bank, val_keys = build_eval_artifacts(splits["val"])

    for epoch in range(1, args.epochs + 1):
        train_metrics = train_one_epoch(model, loaders["train"], optimizer, device, args)
        val_metrics = evaluate(model, loaders["val"], device, val_centroids, val_bank, val_keys)
        val_score = metric_value(val_metrics, args)
        history.append(
            {
                "epoch": float(epoch),
                "train_loss": train_metrics["loss"],
                "train_cosine_loss": train_metrics["cosine_loss"],
                "train_contrastive_loss": train_metrics["contrastive_loss"],
                "train_margin_loss": train_metrics["margin_loss"],
                "val_mean_target_cosine": val_metrics["mean_target_cosine"],
                "val_centroid_stage_accuracy": val_metrics["centroid_stage_accuracy"],
                "val_exact_target_retrieval_at_1": val_metrics["exact_target_retrieval_at_1"],
                "val_exact_target_retrieval_at_5": val_metrics["exact_target_retrieval_at_5"],
                "val_selection_score": val_score,
                "lr": float(optimizer.param_groups[0]["lr"]),
            }
        )

        if val_score > best_val_score:
            best_val_score = val_score
            best_state = {key: value.detach().cpu().clone() for key, value in model.state_dict().items()}
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

        scheduler.step()
        if epochs_without_improvement >= args.patience:
            break

    if best_state is None:
        raise RuntimeError("Training did not produce a valid checkpoint.")

    model.load_state_dict(best_state)
    torch.save(best_state, output_dir / "best_model.pt")

    train_centroids, train_bank, train_keys = build_eval_artifacts(splits["train"])
    test_centroids, test_bank, test_keys = build_eval_artifacts(splits["test"])
    train_metrics = evaluate(model, loaders["train"], device, train_centroids, train_bank, train_keys)
    val_metrics = evaluate(model, loaders["val"], device, val_centroids, val_bank, val_keys)
    test_metrics = evaluate(model, loaders["test"], device, test_centroids, test_bank, test_keys)

    summary = {
        "embeddings_npz": args.embeddings_npz,
        "aux_embeddings_npz": [str(path) for path in aux_embedding_paths],
        "embedding_sources": [str(path) for path in embedding_paths],
        "embedding_alignment": embedding_alignment,
        "manifest_frames": args.manifest_frames,
        "device": str(device),
        "model_config": {
            "sequence_model": "cnn",
            "model_dim": args.model_dim,
            "num_layers": args.num_layers,
            "cnn_kernel_size": args.cnn_kernel_size,
            "cnn_dilation_cycle": args.cnn_dilation_cycle,
            "stage_embed_dim": args.stage_embed_dim,
            "dropout": args.dropout,
            "context_window": args.context_window,
            "num_stages": max_stage_idx + 1,
            "max_seq_len": max_seq_len,
            "stage_head_mode": stage_head_mode,
            "stage_specific_output_heads": (stage_head_mode == "stage-specific"),
        },
        "training_config": {
            "batch_size": args.batch_size,
            "epochs": args.epochs,
            "lr": args.lr,
            "min_lr": args.min_lr,
            "weight_decay": args.weight_decay,
            "feature_transform": feature_transform,
            "feature_output_dim": args.feature_output_dim,
            "embedding_key_alignment": args.embedding_key_alignment,
            "context_window": args.context_window,
            "grad_clip_norm": args.grad_clip_norm,
            "cosine_weight": args.cosine_weight,
            "contrastive_weight": args.contrastive_weight,
            "margin_loss_weight": args.margin_loss_weight,
            "margin_loss_value": args.margin_loss_value,
            "temperature": args.temperature,
            "source_feature_dropout": args.source_feature_dropout,
            "source_noise_std": args.source_noise_std,
            "stage_head_mode": stage_head_mode,
            "selection_metric": args.selection_metric,
            "blend_retrieval_weight": args.blend_retrieval_weight,
            "blend_cosine_weight": args.blend_cosine_weight,
            "patience": args.patience,
            "lr_warmup_epochs": args.lr_warmup_epochs,
            "seed": args.seed,
        },
        "feature_stats": {
            "mean_norm": float(np.linalg.norm(feature_mean)) if feature_mean is not None else None,
            "std_mean": float(np.mean(feature_std)) if feature_std is not None else None,
            "std_min": float(np.min(feature_std)) if feature_std is not None else None,
            "std_max": float(np.max(feature_std)) if feature_std is not None else None,
            "components_shape": list(feature_components.shape) if feature_components is not None else None,
            "scale_mean": float(np.mean(feature_scales)) if feature_scales is not None else None,
            "scale_min": float(np.min(feature_scales)) if feature_scales is not None else None,
            "scale_max": float(np.max(feature_scales)) if feature_scales is not None else None,
            "transform_path": str(output_dir / "feature_transform.npz") if feature_components is not None else None,
        },
        "num_train": len(splits["train"]),
        "num_val": len(splits["val"]),
        "num_test": len(splits["test"]),
        "embedding_dim": transformed_embedding_dim,
        "raw_embedding_dim": embedding_dim,
        "skipped_noncontiguous_examples": skipped_noncontiguous,
        "best_val_selection_score": best_val_score,
        "train_metrics": train_metrics,
        "val_metrics": val_metrics,
        "test_metrics": test_metrics,
        "history": history,
    }
    write_json(output_dir / "metrics.json", summary)

    print("Transition CNN training complete")
    print(f"Train / Val / Test: {len(splits['train'])} / {len(splits['val'])} / {len(splits['test'])}")
    print(f"Max prefix length:   {max_seq_len}")
    print(f"Best val score:      {best_val_score:.4f} ({args.selection_metric})")
    print(f"Test cosine:         {test_metrics['mean_target_cosine']:.4f}")
    print(f"Test stage acc:      {test_metrics['centroid_stage_accuracy']:.4f}")
    print(f"Test retrieval@1:    {test_metrics['exact_target_retrieval_at_1']:.4f}")
    print(f"Test retrieval@5:    {test_metrics['exact_target_retrieval_at_5']:.4f}")
    print(f"Output dir:          {output_dir}")


if __name__ == "__main__":
    main()
