import argparse
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image, ImageDraw
from torch import nn
from torch.utils.data import DataLoader, Dataset

from learning_utils import (
    PixelDecoderUNet,
    TransitionMLP,
    default_device,
    image_to_tensor,
    load_checkpoint_state,
    load_embedding_archive,
    load_model_config,
    ssim_loss,
    sobel_edges,
    tensor_to_pil,
)
from script_utils import LEARNING_ROOT, ensure_dir, read_csv_rows, require_file, write_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train a pixel decoder for one-step owl stage transitions.")
    parser.add_argument(
        "--embeddings-npz",
        default=str(LEARNING_ROOT / "embeddings" / "clip_embeddings_all.npz"),
        help="Path to embedding .npz generated by extract_clip_embeddings.py",
    )
    parser.add_argument(
        "--transitions-csv",
        default=str(LEARNING_ROOT / "manifest_transitions.csv"),
        help="Path to transition manifest CSV from build_manifest.py",
    )
    parser.add_argument(
        "--latent-checkpoint",
        default=str(LEARNING_ROOT / "ar_baseline" / "best_model.pt"),
        help="Path to trained latent transition checkpoint",
    )
    parser.add_argument(
        "--latent-metrics-json",
        default=str(LEARNING_ROOT / "ar_baseline" / "metrics.json"),
        help="Metrics JSON written by train_transition_baseline.py",
    )
    parser.add_argument(
        "--output-dir",
        default=str(LEARNING_ROOT / "pixel_decoder"),
        help="Output directory for decoder artifacts",
    )
    parser.add_argument("--device", default=default_device(), help="Training device")
    parser.add_argument("--image-size", type=int, default=256, help="Square training resolution")
    parser.add_argument("--batch-size", type=int, default=8, help="Mini-batch size")
    parser.add_argument("--epochs", type=int, default=100, help="Maximum number of epochs")
    parser.add_argument("--lr", type=float, default=2e-4, help="Learning rate")
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="AdamW weight decay")
    parser.add_argument("--base-channels", type=int, default=32, help="UNet base channel count")
    parser.add_argument("--cond-dim", type=int, default=256, help="Conditioning MLP width")
    parser.add_argument("--stage-embed-dim", type=int, default=16, help="Learned source-stage embedding size")
    parser.add_argument("--min-src-stage", type=int, default=0, help="Minimum source stage to train")
    parser.add_argument("--max-src-stage", type=int, default=8, help="Maximum source stage to train")
    parser.add_argument(
        "--output-mode",
        choices=["residual", "direct"],
        default="residual",
        help="Residual predicts x_t + delta; direct predicts the full next image",
    )
    parser.add_argument("--residual-scale", type=float, default=1.0, help="Maximum residual delta magnitude")
    parser.add_argument("--l1-weight", type=float, default=1.0, help="L1 reconstruction loss weight")
    parser.add_argument(
        "--delta-weight",
        type=float,
        default=5.0,
        help="Loss weight for predicting the actual target-source image delta",
    )
    parser.add_argument("--ssim-weight", type=float, default=0.5, help="SSIM loss weight")
    parser.add_argument("--lpips-weight", type=float, default=0.0, help="LPIPS loss weight; requires lpips package")
    parser.add_argument("--edge-weight", type=float, default=0.2, help="Sobel edge loss weight")
    parser.add_argument("--edge-max-stage", type=int, default=4, help="Apply edge loss through this source stage")
    parser.add_argument(
        "--change-weight",
        type=float,
        default=8.0,
        help="Extra L1 weight for pixels that change between source and target",
    )
    parser.add_argument(
        "--foreground-weight",
        type=float,
        default=2.0,
        help="Extra L1 weight for non-background target pixels",
    )
    parser.add_argument("--change-threshold", type=float, default=0.03, help="Pixel-change threshold for weighted L1")
    parser.add_argument("--foreground-threshold", type=float, default=0.05, help="Target luminance threshold for weighted L1")
    parser.add_argument(
        "--delta-change-weight",
        type=float,
        default=16.0,
        help="Extra delta loss weight on pixels that should change",
    )
    parser.add_argument(
        "--conditioning-mode",
        choices=["predicted", "target", "mix"],
        default="mix",
        help="Condition decoder on predicted latents, true target latents, or a training mix",
    )
    parser.add_argument(
        "--target-conditioning-prob",
        type=float,
        default=0.5,
        help="Probability of true target latent conditioning when --conditioning-mode mix",
    )
    parser.add_argument("--patience", type=int, default=15, help="Early stopping patience on validation loss")
    parser.add_argument("--num-workers", type=int, default=0, help="DataLoader worker count")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    return parser.parse_args()


def set_seed(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_embedding_lookup(path: Path) -> Tuple[Dict[Tuple[str, int], np.ndarray], int]:
    data = load_embedding_archive(path, normalize=True)
    embeddings = data["embeddings"]
    stems = data["stems"]
    stage_indices = data["stage_indices"]
    lookup: Dict[Tuple[str, int], np.ndarray] = {}
    for stem, stage_idx, emb in zip(stems, stage_indices, embeddings):
        lookup[(str(stem), int(stage_idx))] = emb
    return lookup, int(embeddings.shape[1])


def load_transitions(
    path: Path,
    lookup: Dict[Tuple[str, int], np.ndarray],
    min_src_stage: int,
    max_src_stage: int,
) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    for row in read_csv_rows(path, description="Transition manifest"):
        stem = str(row["stem"])
        src_stage = int(row["src_stage_idx"])
        tgt_stage = int(row["tgt_stage_idx"])
        if src_stage < min_src_stage or src_stage > max_src_stage:
            continue
        src_key = (stem, src_stage)
        tgt_key = (stem, tgt_stage)
        if src_key not in lookup or tgt_key not in lookup:
            raise KeyError(f"Missing embedding lookup for transition {row['transition_key']}")

        src_image_path = Path(row["src_image_path"])
        tgt_image_path = Path(row["tgt_image_path"])
        require_file(src_image_path, "Source image")
        require_file(tgt_image_path, "Target image")

        rows.append(
            {
                "stem": stem,
                "split": row["split"],
                "transition_key": row["transition_key"],
                "src_stage_idx": src_stage,
                "tgt_stage_idx": tgt_stage,
                "src_image_path": str(src_image_path),
                "tgt_image_path": str(tgt_image_path),
                "src_embedding": lookup[src_key],
                "tgt_embedding": lookup[tgt_key],
            }
        )

    if not rows:
        raise RuntimeError("No transition rows loaded.")
    return rows


def split_rows(rows: List[Dict[str, object]]) -> Dict[str, List[Dict[str, object]]]:
    out = {"train": [], "val": [], "test": []}
    for row in rows:
        split = str(row["split"])
        if split in out:
            out[split].append(row)
    for split_name, split_rows_ in out.items():
        if not split_rows_:
            raise RuntimeError(f"No rows found for split: {split_name}")
    return out


class PixelTransitionDataset(Dataset):
    def __init__(self, rows: List[Dict[str, object]], image_size: int):
        self.rows = rows
        self.image_size = image_size

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, idx: int) -> Dict[str, object]:
        row = self.rows[idx]
        with Image.open(str(row["src_image_path"])) as image:
            src_image = image_to_tensor(image, self.image_size)
        with Image.open(str(row["tgt_image_path"])) as image:
            tgt_image = image_to_tensor(image, self.image_size)

        return {
            "src_image": src_image,
            "tgt_image": tgt_image,
            "src_embedding": torch.from_numpy(np.asarray(row["src_embedding"], dtype=np.float32)),
            "tgt_embedding": torch.from_numpy(np.asarray(row["tgt_embedding"], dtype=np.float32)),
            "src_stage_idx": torch.tensor(int(row["src_stage_idx"]), dtype=torch.long),
            "tgt_stage_idx": torch.tensor(int(row["tgt_stage_idx"]), dtype=torch.long),
            "transition_key": str(row["transition_key"]),
        }


def build_latent_model(config_path: Path, checkpoint_path: Path, embedding_dim: int, device: torch.device) -> TransitionMLP:
    model_config = load_model_config(config_path)
    model = TransitionMLP(
        embedding_dim=embedding_dim,
        hidden_dim=int(model_config["hidden_dim"]),
        stage_embed_dim=int(model_config["stage_embed_dim"]),
        dropout=float(model_config["dropout"]),
        num_stages=int(model_config["num_stages"]),
    ).to(device)
    model.load_state_dict(load_checkpoint_state(checkpoint_path, device))
    model.eval()
    for parameter in model.parameters():
        parameter.requires_grad_(False)
    return model


def build_lpips(weight: float, device: torch.device):
    if weight <= 0.0:
        return None
    try:
        import lpips
    except Exception as exc:
        raise RuntimeError("LPIPS requested, but the lpips package is not installed.") from exc

    model = lpips.LPIPS(net="alex").to(device)
    model.eval()
    for parameter in model.parameters():
        parameter.requires_grad_(False)
    return model


def compute_loss(
    src: torch.Tensor,
    pred: torch.Tensor,
    pred_delta: torch.Tensor,
    target: torch.Tensor,
    src_stage: torch.Tensor,
    lpips_model,
    args: argparse.Namespace,
) -> Tuple[torch.Tensor, Dict[str, float]]:
    target_delta = target - src
    per_pixel_l1 = torch.abs(pred - target)
    change = torch.mean(torch.abs(target_delta), dim=1, keepdim=True) > float(args.change_threshold)
    target_luma = 0.299 * target[:, 0:1] + 0.587 * target[:, 1:2] + 0.114 * target[:, 2:3]
    foreground = target_luma > float(args.foreground_threshold)
    weights = (
        1.0
        + float(args.change_weight) * change.to(dtype=pred.dtype)
        + float(args.foreground_weight) * foreground.to(dtype=pred.dtype)
    )
    l1 = torch.mean(per_pixel_l1 * weights)
    unweighted_l1 = F.l1_loss(pred, target)
    delta_weights = 1.0 + float(args.delta_change_weight) * change.to(dtype=pred.dtype)
    delta_l1 = torch.mean(torch.abs(pred_delta - target_delta) * delta_weights)
    ssim = ssim_loss(pred, target)

    early_mask = src_stage <= int(args.edge_max_stage)
    if torch.any(early_mask):
        edge = F.l1_loss(sobel_edges(pred[early_mask]), sobel_edges(target[early_mask]))
    else:
        edge = pred.new_tensor(0.0)

    if lpips_model is not None:
        lpips_value = lpips_model(pred * 2.0 - 1.0, target * 2.0 - 1.0).mean()
    else:
        lpips_value = pred.new_tensor(0.0)

    total = (
        float(args.l1_weight) * l1
        + float(args.delta_weight) * delta_l1
        + float(args.ssim_weight) * ssim
        + float(args.edge_weight) * edge
        + float(args.lpips_weight) * lpips_value
    )
    return total, {
        "loss": float(total.detach().cpu().item()),
        "l1": float(l1.detach().cpu().item()),
        "unweighted_l1": float(unweighted_l1.detach().cpu().item()),
        "delta_l1": float(delta_l1.detach().cpu().item()),
        "ssim": float(ssim.detach().cpu().item()),
        "edge": float(edge.detach().cpu().item()),
        "lpips": float(lpips_value.detach().cpu().item()),
    }


def mean_metrics(values: List[Dict[str, float]]) -> Dict[str, float]:
    if not values:
        return {
            "loss": float("nan"),
            "l1": float("nan"),
            "unweighted_l1": float("nan"),
            "delta_l1": float("nan"),
            "ssim": float("nan"),
            "edge": float("nan"),
            "lpips": float("nan"),
        }
    keys = values[0].keys()
    return {key: float(np.mean([item[key] for item in values])) for key in keys}


def choose_condition_embedding(
    latent_model: nn.Module,
    src_embedding: torch.Tensor,
    tgt_embedding: torch.Tensor,
    src_stage: torch.Tensor,
    args: argparse.Namespace,
    training: bool,
) -> torch.Tensor:
    with torch.no_grad():
        pred_embedding = latent_model(src_embedding, src_stage)

    if args.conditioning_mode == "predicted" or not training:
        return pred_embedding
    if args.conditioning_mode == "target":
        return tgt_embedding

    prob = float(args.target_conditioning_prob)
    if prob <= 0.0:
        return pred_embedding
    if prob >= 1.0:
        return tgt_embedding

    mask = torch.rand((src_embedding.shape[0], 1), device=src_embedding.device) < prob
    return torch.where(mask, tgt_embedding, pred_embedding)


def train_one_epoch(
    decoder: nn.Module,
    latent_model: nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    lpips_model,
    args: argparse.Namespace,
) -> Dict[str, float]:
    decoder.train()
    losses: List[Dict[str, float]] = []

    for batch in loader:
        src_image = batch["src_image"].to(device)
        tgt_image = batch["tgt_image"].to(device)
        src_embedding = batch["src_embedding"].to(device)
        tgt_embedding = batch["tgt_embedding"].to(device)
        src_stage = batch["src_stage_idx"].to(device)

        cond_embedding = choose_condition_embedding(latent_model, src_embedding, tgt_embedding, src_stage, args, training=True)
        pred_image, pred_delta = decoder(src_image, cond_embedding, src_stage, return_delta=True)
        loss, metrics = compute_loss(src_image, pred_image, pred_delta, tgt_image, src_stage, lpips_model, args)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        losses.append(metrics)

    return mean_metrics(losses)


def evaluate(
    decoder: nn.Module,
    latent_model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    lpips_model,
    args: argparse.Namespace,
) -> Tuple[Dict[str, float], Dict[str, Dict[str, float]]]:
    decoder.eval()
    losses: List[Dict[str, float]] = []
    by_transition: Dict[str, List[Dict[str, float]]] = {}

    with torch.no_grad():
        for batch in loader:
            src_image = batch["src_image"].to(device)
            tgt_image = batch["tgt_image"].to(device)
            src_embedding = batch["src_embedding"].to(device)
            tgt_embedding = batch["tgt_embedding"].to(device)
            src_stage = batch["src_stage_idx"].to(device)
            tgt_stage = batch["tgt_stage_idx"].to(device)

            cond_embedding = choose_condition_embedding(latent_model, src_embedding, tgt_embedding, src_stage, args, training=False)
            pred_image, pred_delta = decoder(src_image, cond_embedding, src_stage, return_delta=True)
            _, metrics = compute_loss(src_image, pred_image, pred_delta, tgt_image, src_stage, lpips_model, args)
            losses.append(metrics)

            per_sample_l1 = torch.mean(torch.abs(pred_image - tgt_image), dim=(1, 2, 3)).detach().cpu().numpy()
            src_np = src_stage.detach().cpu().numpy()
            tgt_np = tgt_stage.detach().cpu().numpy()
            for idx, l1_value in enumerate(per_sample_l1):
                key = f"{int(src_np[idx])}_to_{int(tgt_np[idx])}"
                by_transition.setdefault(key, []).append({"l1": float(l1_value)})

    transition_metrics = {key: mean_metrics(values) for key, values in by_transition.items()}
    return mean_metrics(losses), transition_metrics


def save_sample_sheet(
    decoder: nn.Module,
    latent_model: nn.Module,
    dataset: PixelTransitionDataset,
    device: torch.device,
    output_path: Path,
    max_samples: int = 6,
) -> None:
    decoder.eval()
    count = min(max_samples, len(dataset))
    if count == 0:
        return

    tile_size = 160
    label_height = 22
    sheet = Image.new("RGB", (tile_size * 4, count * (tile_size + label_height)), color=(255, 255, 255))
    draw = ImageDraw.Draw(sheet)

    with torch.no_grad():
        for row_idx in range(count):
            sample = dataset[row_idx]
            src_image = sample["src_image"].unsqueeze(0).to(device)
            src_embedding = sample["src_embedding"].unsqueeze(0).to(device)
            tgt_embedding = sample["tgt_embedding"].unsqueeze(0).to(device)
            src_stage = sample["src_stage_idx"].view(1).to(device)
            cond_embedding = choose_condition_embedding(latent_model, src_embedding, tgt_embedding, src_stage, argparse.Namespace(conditioning_mode="predicted"), training=False)
            pred_image, pred_delta = decoder(src_image, cond_embedding, src_stage, return_delta=True)
            pred_image = pred_image[0]
            pred_delta_vis = torch.clamp(pred_delta[0] * 0.5 + 0.5, 0.0, 1.0)

            images = [
                tensor_to_pil(sample["src_image"]),
                tensor_to_pil(pred_image),
                tensor_to_pil(sample["tgt_image"]),
                tensor_to_pil(pred_delta_vis),
            ]
            labels = ["source", "predicted", "target", "delta"]
            y = row_idx * (tile_size + label_height)
            for col_idx, (image, label) in enumerate(zip(images, labels)):
                image = image.resize((tile_size, tile_size), Image.BICUBIC)
                x = col_idx * tile_size
                sheet.paste(image, (x, y))
                draw.text((x + 6, y + tile_size + 4), label, fill=(0, 0, 0))

    ensure_dir(output_path.parent)
    sheet.save(output_path)


def main() -> None:
    args = parse_args()
    set_seed(args.seed)

    output_dir = ensure_dir(Path(args.output_dir))
    device = torch.device(args.device)

    lookup, embedding_dim = load_embedding_lookup(Path(args.embeddings_npz))
    rows = load_transitions(Path(args.transitions_csv), lookup, args.min_src_stage, args.max_src_stage)
    splits = split_rows(rows)

    datasets = {name: PixelTransitionDataset(split_rows_, args.image_size) for name, split_rows_ in splits.items()}
    loaders = {
        "train": DataLoader(datasets["train"], batch_size=args.batch_size, shuffle=True, num_workers=args.num_workers),
        "val": DataLoader(datasets["val"], batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers),
        "test": DataLoader(datasets["test"], batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers),
    }

    max_stage_idx = max(int(row["tgt_stage_idx"]) for row in rows)
    latent_model = build_latent_model(Path(args.latent_metrics_json), Path(args.latent_checkpoint), embedding_dim, device)
    decoder = PixelDecoderUNet(
        embedding_dim=embedding_dim,
        num_stages=max_stage_idx + 1,
        base_channels=args.base_channels,
        stage_embed_dim=args.stage_embed_dim,
        cond_dim=args.cond_dim,
        output_mode=args.output_mode,
        residual_scale=args.residual_scale,
    ).to(device)
    lpips_model = build_lpips(args.lpips_weight, device)
    optimizer = torch.optim.AdamW(decoder.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    best_state = None
    best_val_loss = float("inf")
    epochs_without_improvement = 0
    history: List[Dict[str, float]] = []

    for epoch in range(1, args.epochs + 1):
        train_metrics = train_one_epoch(decoder, latent_model, loaders["train"], optimizer, device, lpips_model, args)
        val_metrics, _ = evaluate(decoder, latent_model, loaders["val"], device, lpips_model, args)
        epoch_summary = {
            "epoch": float(epoch),
            **{f"train_{key}": value for key, value in train_metrics.items()},
            **{f"val_{key}": value for key, value in val_metrics.items()},
        }
        history.append(epoch_summary)

        if val_metrics["loss"] < best_val_loss:
            best_val_loss = val_metrics["loss"]
            best_state = {key: value.detach().cpu().clone() for key, value in decoder.state_dict().items()}
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

        print(
            f"epoch {epoch:03d} "
            f"train_loss={train_metrics['loss']:.4f} "
            f"val_loss={val_metrics['loss']:.4f} "
            f"val_l1={val_metrics['l1']:.4f} "
            f"val_delta={val_metrics['delta_l1']:.4f}"
        )

        if epochs_without_improvement >= args.patience:
            break

    if best_state is None:
        raise RuntimeError("Training did not produce a valid decoder checkpoint.")

    decoder.load_state_dict(best_state)
    checkpoint = {
        "model_state_dict": best_state,
        "model_config": {
            "embedding_dim": embedding_dim,
            "num_stages": max_stage_idx + 1,
            "base_channels": args.base_channels,
            "stage_embed_dim": args.stage_embed_dim,
            "cond_dim": args.cond_dim,
            "image_size": args.image_size,
            "output_mode": args.output_mode,
            "residual_scale": args.residual_scale,
            "min_src_stage": args.min_src_stage,
            "max_src_stage": args.max_src_stage,
        },
    }
    torch.save(checkpoint, output_dir / "best_pixel_decoder.pt")

    train_metrics, train_by_transition = evaluate(decoder, latent_model, loaders["train"], device, lpips_model, args)
    val_metrics, val_by_transition = evaluate(decoder, latent_model, loaders["val"], device, lpips_model, args)
    test_metrics, test_by_transition = evaluate(decoder, latent_model, loaders["test"], device, lpips_model, args)
    save_sample_sheet(decoder, latent_model, datasets["val"], device, output_dir / "val_samples.png")

    summary = {
        "embeddings_npz": args.embeddings_npz,
        "transitions_csv": args.transitions_csv,
        "latent_checkpoint": args.latent_checkpoint,
        "latent_metrics_json": args.latent_metrics_json,
        "device": str(device),
        "model_config": checkpoint["model_config"],
        "loss_weights": {
            "l1": args.l1_weight,
            "delta": args.delta_weight,
            "ssim": args.ssim_weight,
            "lpips": args.lpips_weight,
            "edge": args.edge_weight,
            "edge_max_stage": args.edge_max_stage,
            "change": args.change_weight,
            "foreground": args.foreground_weight,
            "change_threshold": args.change_threshold,
            "foreground_threshold": args.foreground_threshold,
            "delta_change": args.delta_change_weight,
            "conditioning_mode": args.conditioning_mode,
            "target_conditioning_prob": args.target_conditioning_prob,
        },
        "num_train": len(splits["train"]),
        "num_val": len(splits["val"]),
        "num_test": len(splits["test"]),
        "best_val_loss": best_val_loss,
        "train_metrics": train_metrics,
        "val_metrics": val_metrics,
        "test_metrics": test_metrics,
        "train_by_transition": train_by_transition,
        "val_by_transition": val_by_transition,
        "test_by_transition": test_by_transition,
        "history": history,
    }
    write_json(output_dir / "metrics.json", summary)

    print("Pixel decoder training complete")
    print(f"Train / Val / Test: {len(splits['train'])} / {len(splits['val'])} / {len(splits['test'])}")
    print(f"Best val loss:      {best_val_loss:.4f}")
    print(f"Test loss:          {test_metrics['loss']:.4f}")
    print(f"Test L1:            {test_metrics['l1']:.4f}")
    print(f"Output dir:         {output_dir}")


if __name__ == "__main__":
    main()
