import argparse
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import torch
import torch.nn.functional as F
from torch import nn
from torch.utils.data import DataLoader, Dataset

from learning_utils import (
    TransitionSequenceTransformer,
    default_device,
    load_embedding_archive,
    normalize_rows,
)
from script_utils import LEARNING_ROOT, ensure_dir, read_csv_rows, write_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a transformer next-stage predictor on stage trajectories with contrastive learning."
    )
    parser.add_argument(
        "--embeddings-npz",
        default=str(LEARNING_ROOT / "embeddings" / "dino_embeddings_all.npz"),
        help="Path to embedding .npz generated by the embedding extraction scripts",
    )
    parser.add_argument(
        "--aux-embeddings-npz",
        nargs="*",
        default=[],
        help="Optional additional embedding archives to concatenate with the primary archive",
    )
    parser.add_argument(
        "--embedding-key-alignment",
        choices=["intersection", "strict"],
        default="intersection",
        help="How to align multiple embedding archives when their (stem, stage_idx) coverage differs",
    )
    parser.add_argument(
        "--manifest-frames",
        default=str(LEARNING_ROOT / "manifest_frames.csv"),
        help="Path to frame manifest CSV from build_manifest.py",
    )
    parser.add_argument(
        "--output-dir",
        default=str(LEARNING_ROOT / "transition_transformer_contrastive"),
        help="Output directory for training artifacts",
    )
    parser.add_argument("--device", default=default_device(), help="Training device")
    parser.add_argument("--batch-size", type=int, default=64, help="Mini-batch size")
    parser.add_argument("--epochs", type=int, default=250, help="Maximum number of epochs")
    parser.add_argument("--lr", type=float, default=3e-4, help="Learning rate")
    parser.add_argument("--min-lr", type=float, default=1e-5, help="Minimum LR for cosine annealing")
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="AdamW weight decay")
    parser.add_argument(
        "--feature-transform",
        choices=["auto", "none", "standardize", "pca", "pca_whiten"],
        default="auto",
        help="Optional train-split feature transform applied before row normalization",
    )
    parser.add_argument(
        "--feature-output-dim",
        type=int,
        default=256,
        help="Output dimension for PCA-based feature transforms (ignored otherwise)",
    )
    parser.add_argument(
        "--context-window",
        type=int,
        default=3,
        help="Use only the most recent K source stages in each prefix (0 keeps the full prefix)",
    )
    parser.add_argument("--model-dim", type=int, default=256, help="Transformer hidden size")
    parser.add_argument("--num-layers", type=int, default=2, help="Number of transformer encoder layers")
    parser.add_argument("--num-heads", type=int, default=4, help="Number of attention heads")
    parser.add_argument("--ff-dim", type=int, default=512, help="Feed-forward width inside transformer blocks")
    parser.add_argument("--stage-embed-dim", type=int, default=32, help="Stage embedding size before projection")
    parser.add_argument("--dropout", type=float, default=0.1, help="Dropout in the transformer")
    parser.add_argument(
        "--source-feature-dropout",
        type=float,
        default=0.0,
        help="Dropout applied to source embedding features during training",
    )
    parser.add_argument(
        "--source-noise-std",
        type=float,
        default=0.0,
        help="Gaussian noise std added to source embeddings during training before renormalization",
    )
    parser.add_argument(
        "--disable-stage-specific-output-heads",
        action="store_true",
        help="Use shared output heads instead of source-stage-specific output heads",
    )
    parser.add_argument(
        "--stage-head-mode",
        choices=["auto", "shared", "stage-specific"],
        default="auto",
        help="Whether to use shared or source-stage-specific output heads",
    )
    parser.add_argument("--grad-clip-norm", type=float, default=1.0, help="Gradient clipping norm; <= 0 disables clipping")
    parser.add_argument("--cosine-weight", type=float, default=0.25, help="Weight for cosine regression loss")
    parser.add_argument("--contrastive-weight", type=float, default=1.0, help="Weight for InfoNCE retrieval loss")
    parser.add_argument(
        "--margin-loss-weight",
        type=float,
        default=0.0,
        help="Weight for a same-stage hard-negative margin loss that sharpens retrieval@1",
    )
    parser.add_argument(
        "--margin-loss-value",
        type=float,
        default=0.04,
        help="Required margin between the correct target and the hardest same-stage negative",
    )
    parser.add_argument("--temperature", type=float, default=0.07, help="Temperature for contrastive retrieval loss")
    parser.add_argument(
        "--selection-metric",
        choices=["retrieval_at_1", "cosine", "blended"],
        default="retrieval_at_1",
        help="Validation metric used for checkpoint selection and early stopping",
    )
    parser.add_argument("--blend-retrieval-weight", type=float, default=0.85, help="Retrieval weight in blended checkpoint selection")
    parser.add_argument("--blend-cosine-weight", type=float, default=0.15, help="Cosine weight in blended checkpoint selection")
    parser.add_argument("--patience", type=int, default=30, help="Early stopping patience on the selected validation metric")
    parser.add_argument("--lr-warmup-epochs", type=int, default=10, help="Number of warmup epochs before cosine annealing")
    parser.add_argument("--num-workers", type=int, default=0, help="DataLoader worker count")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    return parser.parse_args()


def set_seed(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_embedding_lookup(path: Path) -> Tuple[Dict[Tuple[str, int], np.ndarray], int]:
    data = load_embedding_archive(path, normalize=True)
    embeddings = data["embeddings"]
    stems = data["stems"]
    stage_indices = data["stage_indices"]
    lookup: Dict[Tuple[str, int], np.ndarray] = {}
    for stem, stage_idx, emb in zip(stems, stage_indices, embeddings):
        lookup[(str(stem), int(stage_idx))] = emb
    return lookup, int(embeddings.shape[1])


def load_combined_embedding_lookup(
    paths: List[Path],
    alignment: str = "intersection",
) -> Tuple[Dict[Tuple[str, int], np.ndarray], int, Dict[str, object]]:
    if not paths:
        raise ValueError("Expected at least one embedding archive path")

    per_path: List[Tuple[Dict[Tuple[str, int], np.ndarray], int]] = [load_embedding_lookup(path) for path in paths]
    base_lookup, base_dim = per_path[0]
    all_key_sets = [set(lookup.keys()) for lookup, _ in per_path]
    if alignment == "strict":
        keys = list(base_lookup.keys())
    else:
        shared_keys = set.intersection(*all_key_sets)
        keys = [key for key in base_lookup.keys() if key in shared_keys]

    dropped_per_archive = []
    for path, (lookup, _), key_set in zip(paths, per_path, all_key_sets):
        dropped = sorted(key_set.difference(keys))
        dropped_per_archive.append(
            {
                "path": str(path),
                "num_keys": int(len(key_set)),
                "num_used_keys": int(len(keys)),
                "num_dropped_keys": int(len(dropped)),
                "sample_dropped_keys": [(str(stem), int(stage_idx)) for stem, stage_idx in dropped[:10]],
            }
        )

    combined_lookup: Dict[Tuple[str, int], np.ndarray] = {}
    total_dim = int(sum(dim for _, dim in per_path))

    for lookup, _ in per_path[1:]:
        missing = [key for key in keys if key not in lookup]
        extra = [key for key in lookup.keys() if key not in base_lookup]
        if alignment == "strict" and (missing or extra):
            raise RuntimeError(
                "Embedding archives do not align on (stem, stage_idx). "
                f"Missing in one archive: {missing[:3]}. Extra in one archive: {extra[:3]}."
            )

    for key in keys:
        parts = [np.asarray(lookup[key], dtype=np.float32) for lookup, _ in per_path]
        combined = np.concatenate(parts, axis=0).astype(np.float32)
        combined /= max(float(np.linalg.norm(combined)), 1e-12)
        combined_lookup[key] = combined

    alignment_info = {
        "mode": alignment,
        "num_shared_keys": int(len(keys)),
        "archives": dropped_per_archive,
    }
    return combined_lookup, total_dim, alignment_info


def load_frame_rows(path: Path, lookup: Dict[Tuple[str, int], np.ndarray]) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    for row in read_csv_rows(path, description="Frame manifest"):
        stem = str(row["stem"])
        stage_idx = int(row["stage_idx"])
        key = (stem, stage_idx)
        if key not in lookup:
            raise KeyError(f"Missing embedding lookup for frame {row['frame_key']}")
        rows.append(
            {
                "stem": stem,
                "split": str(row["split"]),
                "stage_idx": stage_idx,
                "frame_key": str(row["frame_key"]),
                "embedding": lookup[key],
            }
        )
    if not rows:
        raise RuntimeError("No frame rows loaded.")
    return rows


def build_prefix_examples(frame_rows: List[Dict[str, object]], context_window: int) -> Tuple[List[Dict[str, object]], int]:
    by_stem: Dict[str, List[Dict[str, object]]] = {}
    for row in frame_rows:
        by_stem.setdefault(str(row["stem"]), []).append(row)

    examples: List[Dict[str, object]] = []
    skipped_noncontiguous = 0
    for stem, stem_rows in by_stem.items():
        stem_rows = sorted(stem_rows, key=lambda row: int(row["stage_idx"]))
        splits = {str(row["split"]) for row in stem_rows}
        if len(splits) != 1:
            raise RuntimeError(f"Expected a single split per stem, got {splits} for stem {stem}")

        for idx in range(len(stem_rows) - 1):
            prefix_rows_full = stem_rows[: idx + 1]
            prefix_stages_full = [int(row["stage_idx"]) for row in prefix_rows_full]
            tgt_row = stem_rows[idx + 1]
            expected_prefix = list(range(prefix_stages_full[0], prefix_stages_full[0] + len(prefix_stages_full)))
            if prefix_stages_full != expected_prefix or int(tgt_row["stage_idx"]) != prefix_stages_full[-1] + 1:
                skipped_noncontiguous += 1
                continue

            prefix_rows = prefix_rows_full[-context_window:] if int(context_window) > 0 else prefix_rows_full
            prefix_stages = [int(row["stage_idx"]) for row in prefix_rows]
            src_stage_idx = prefix_stages[-1]
            tgt_stage_idx = int(tgt_row["stage_idx"])
            examples.append(
                {
                    "stem": stem,
                    "split": str(prefix_rows[0]["split"]),
                    "src_stage_idx": src_stage_idx,
                    "tgt_stage_idx": tgt_stage_idx,
                    "transition_key": f"{stem}_stage{src_stage_idx:02d}_to_stage{tgt_stage_idx:02d}",
                    "src_embeddings": np.stack(
                        [np.asarray(row["embedding"], dtype=np.float32) for row in prefix_rows],
                        axis=0,
                    ),
                    "src_stage_indices": np.asarray(prefix_stages, dtype=np.int64),
                    "tgt_embedding": np.asarray(tgt_row["embedding"], dtype=np.float32),
                }
            )

    if not examples:
        raise RuntimeError("No prefix examples could be built from manifest_frames.csv")
    return examples, skipped_noncontiguous


def split_rows(rows: List[Dict[str, object]]) -> Dict[str, List[Dict[str, object]]]:
    out = {"train": [], "val": [], "test": []}
    for row in rows:
        split = str(row["split"])
        if split in out:
            out[split].append(row)
    for split_name, split_rows in out.items():
        if not split_rows:
            raise RuntimeError(f"No rows found for split: {split_name}")
    return out


def resolve_feature_transform(mode: str, embeddings_path: Path) -> str:
    if mode != "auto":
        return mode
    return "standardize" if "dino" in embeddings_path.name.lower() else "none"


def resolve_stage_head_mode(mode: str, disable_stage_specific_output_heads: bool, embeddings_path: Path) -> str:
    if disable_stage_specific_output_heads:
        return "shared"
    if mode != "auto":
        return mode
    return "shared" if "dino" in embeddings_path.name.lower() else "stage-specific"


def fit_standardization(rows: List[Dict[str, object]]) -> Tuple[np.ndarray, np.ndarray]:
    vectors: List[np.ndarray] = []
    for row in rows:
        vectors.append(np.asarray(row["src_embeddings"], dtype=np.float32))
        vectors.append(np.asarray(row["tgt_embedding"], dtype=np.float32)[None, :])
    stack = np.concatenate(vectors, axis=0).astype(np.float32)
    mean = stack.mean(axis=0, dtype=np.float32)
    std = stack.std(axis=0, dtype=np.float32)
    std = np.maximum(std, 1e-6).astype(np.float32)
    return mean.astype(np.float32), std


def fit_pca_transform(
    rows: List[Dict[str, object]],
    output_dim: int,
    whiten: bool,
) -> Dict[str, np.ndarray | int | bool]:
    vectors: List[np.ndarray] = []
    for row in rows:
        vectors.append(np.asarray(row["src_embeddings"], dtype=np.float32))
        vectors.append(np.asarray(row["tgt_embedding"], dtype=np.float32)[None, :])
    stack = np.concatenate(vectors, axis=0).astype(np.float32)
    mean = stack.mean(axis=0, dtype=np.float32)
    centered = stack - mean[None, :]

    _, singular_values, vt = np.linalg.svd(centered, full_matrices=False)
    max_dim = int(min(centered.shape[0] - 1, centered.shape[1]))
    if max_dim <= 0:
        raise RuntimeError("Not enough samples to fit PCA transform.")
    proj_dim = int(min(output_dim if output_dim > 0 else centered.shape[1], max_dim))
    components = vt[:proj_dim].T.astype(np.float32)

    denom = max(centered.shape[0] - 1, 1)
    explained_variance = (singular_values[:proj_dim].astype(np.float32) ** 2) / float(denom)
    scales = np.sqrt(np.maximum(explained_variance, 1e-6)).astype(np.float32) if whiten else np.ones((proj_dim,), dtype=np.float32)
    return {
        "mean": mean.astype(np.float32),
        "components": components,
        "scales": scales,
        "output_dim": int(proj_dim),
        "whiten": bool(whiten),
    }


def transform_rows_standardize(rows: List[Dict[str, object]], mean: np.ndarray, std: np.ndarray) -> List[Dict[str, object]]:
    out: List[Dict[str, object]] = []
    for row in rows:
        src_embeddings = np.asarray(row["src_embeddings"], dtype=np.float32)
        tgt_embedding = np.asarray(row["tgt_embedding"], dtype=np.float32)
        src_embeddings = normalize_rows((src_embeddings - mean[None, :]) / std[None, :]).astype(np.float32)
        tgt_embedding = normalize_rows(((tgt_embedding[None, :] - mean[None, :]) / std[None, :]).astype(np.float32))[0]

        out.append(
            {
                **row,
                "src_embeddings": src_embeddings,
                "tgt_embedding": tgt_embedding.astype(np.float32),
            }
        )
    return out


def transform_rows_pca(
    rows: List[Dict[str, object]],
    mean: np.ndarray,
    components: np.ndarray,
    scales: np.ndarray,
) -> List[Dict[str, object]]:
    def project(x: np.ndarray) -> np.ndarray:
        centered = x - mean
        projected = centered @ components
        projected = projected / scales
        return projected.astype(np.float32)

    out: List[Dict[str, object]] = []
    for row in rows:
        src_embeddings = np.asarray(row["src_embeddings"], dtype=np.float32)
        tgt_embedding = np.asarray(row["tgt_embedding"], dtype=np.float32)
        src_projected = np.stack([project(vec) for vec in src_embeddings], axis=0)
        tgt_projected = project(tgt_embedding)
        src_projected = normalize_rows(src_projected).astype(np.float32)
        tgt_projected = normalize_rows(tgt_projected[None, :])[0].astype(np.float32)
        out.append(
            {
                **row,
                "src_embeddings": src_projected,
                "tgt_embedding": tgt_projected,
            }
        )
    return out


class PrefixTransitionDataset(Dataset):
    def __init__(self, rows: List[Dict[str, object]]):
        self.rows = rows

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, idx: int) -> Dict[str, object]:
        row = self.rows[idx]
        return {
            "src_embeddings": torch.from_numpy(np.asarray(row["src_embeddings"], dtype=np.float32)),
            "src_stage_indices": torch.from_numpy(np.asarray(row["src_stage_indices"], dtype=np.int64)),
            "tgt_embedding": torch.from_numpy(np.asarray(row["tgt_embedding"], dtype=np.float32)),
            "src_stage_idx": torch.tensor(int(row["src_stage_idx"]), dtype=torch.long),
            "tgt_stage_idx": torch.tensor(int(row["tgt_stage_idx"]), dtype=torch.long),
            "transition_key": str(row["transition_key"]),
        }


def collate_prefix_batch(batch: List[Dict[str, object]]) -> Dict[str, object]:
    batch_size = len(batch)
    max_len = max(int(item["src_embeddings"].shape[0]) for item in batch)
    embedding_dim = int(batch[0]["src_embeddings"].shape[1])

    src_embeddings = torch.zeros((batch_size, max_len, embedding_dim), dtype=torch.float32)
    src_stage_indices = torch.zeros((batch_size, max_len), dtype=torch.long)
    src_padding_mask = torch.ones((batch_size, max_len), dtype=torch.bool)
    tgt_embeddings = torch.zeros((batch_size, embedding_dim), dtype=torch.float32)
    src_stage_idx = torch.zeros((batch_size,), dtype=torch.long)
    tgt_stage_idx = torch.zeros((batch_size,), dtype=torch.long)
    transition_keys: List[str] = []

    for row_idx, item in enumerate(batch):
        seq_embeddings = item["src_embeddings"]
        seq_stages = item["src_stage_indices"]
        seq_len = int(seq_embeddings.shape[0])
        src_embeddings[row_idx, :seq_len] = seq_embeddings
        src_stage_indices[row_idx, :seq_len] = seq_stages
        src_padding_mask[row_idx, :seq_len] = False
        tgt_embeddings[row_idx] = item["tgt_embedding"]
        src_stage_idx[row_idx] = item["src_stage_idx"]
        tgt_stage_idx[row_idx] = item["tgt_stage_idx"]
        transition_keys.append(str(item["transition_key"]))

    return {
        "src_embeddings": src_embeddings,
        "src_stage_indices": src_stage_indices,
        "src_padding_mask": src_padding_mask,
        "tgt_embedding": tgt_embeddings,
        "src_stage_idx": src_stage_idx,
        "tgt_stage_idx": tgt_stage_idx,
        "transition_key": transition_keys,
    }


def build_stage_centroids(rows: List[Dict[str, object]]) -> Dict[int, np.ndarray]:
    by_stage: Dict[int, List[np.ndarray]] = {}
    for row in rows:
        stage = int(row["tgt_stage_idx"])
        by_stage.setdefault(stage, []).append(np.asarray(row["tgt_embedding"], dtype=np.float32))

    centroids: Dict[int, np.ndarray] = {}
    for stage, vecs in by_stage.items():
        stack = normalize_rows(np.stack(vecs, axis=0))
        centroid = stack.mean(axis=0, dtype=np.float32)
        centroid /= max(float(np.linalg.norm(centroid)), 1e-12)
        centroids[stage] = centroid.astype(np.float32)
    return centroids


def collect_target_bank(rows: List[Dict[str, object]]) -> Tuple[np.ndarray, List[str]]:
    embeddings = []
    keys = []
    for row in rows:
        embeddings.append(np.asarray(row["tgt_embedding"], dtype=np.float32))
        keys.append(str(row["transition_key"]))
    return normalize_rows(np.stack(embeddings, axis=0)), keys


def build_eval_artifacts(rows: List[Dict[str, object]]) -> Tuple[Dict[int, np.ndarray], np.ndarray, List[str]]:
    return build_stage_centroids(rows), *collect_target_bank(rows)


def retrieval_contrastive_loss(
    pred: torch.Tensor,
    tgt: torch.Tensor,
    temperature: float,
) -> torch.Tensor:
    logits = (pred @ tgt.T) / float(temperature)
    labels = torch.arange(logits.shape[0], device=logits.device)
    return 0.5 * (
        F.cross_entropy(logits, labels)
        + F.cross_entropy(logits.T, labels)
    )


def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    args: argparse.Namespace,
) -> Dict[str, float]:
    model.train()
    losses: List[Dict[str, float]] = []

    for batch in loader:
        src_embeddings = batch["src_embeddings"].to(device)
        src_stage_indices = batch["src_stage_indices"].to(device)
        src_padding_mask = batch["src_padding_mask"].to(device)
        tgt_embedding = batch["tgt_embedding"].to(device)

        valid_mask = (~src_padding_mask).unsqueeze(-1).to(dtype=src_embeddings.dtype)
        if float(args.source_feature_dropout) > 0.0:
            src_embeddings = F.dropout(src_embeddings, p=float(args.source_feature_dropout), training=True)
        if float(args.source_noise_std) > 0.0:
            src_embeddings = src_embeddings + torch.randn_like(src_embeddings) * float(args.source_noise_std) * valid_mask
        src_embeddings = F.normalize(src_embeddings * valid_mask, p=2, dim=-1)

        pred = model(src_embeddings, src_stage_indices, src_padding_mask)
        cosine_loss = 1.0 - torch.sum(pred * tgt_embedding, dim=-1).mean()
        contrastive_loss = retrieval_contrastive_loss(pred, tgt_embedding, args.temperature)
        margin_loss = cosine_loss.new_tensor(0.0)
        loss = (
            float(args.cosine_weight) * cosine_loss
            + float(args.contrastive_weight) * contrastive_loss
            + float(args.margin_loss_weight) * margin_loss
        )

        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        if float(args.grad_clip_norm) > 0.0:
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=float(args.grad_clip_norm))
        optimizer.step()
        losses.append(
            {
                "loss": float(loss.detach().cpu().item()),
                "cosine_loss": float(cosine_loss.detach().cpu().item()),
                "contrastive_loss": float(contrastive_loss.detach().cpu().item()),
                "margin_loss": float(margin_loss.detach().cpu().item()),
            }
        )

    if not losses:
        return {"loss": float("nan"), "cosine_loss": float("nan"), "contrastive_loss": float("nan"), "margin_loss": float("nan")}
    keys = losses[0].keys()
    return {key: float(np.mean([item[key] for item in losses])) for key in keys}


def make_lr_scheduler(optimizer: torch.optim.Optimizer, args: argparse.Namespace):
    warmup_epochs = max(int(args.lr_warmup_epochs), 0)
    total_epochs = max(int(args.epochs), 1)
    min_lr = float(args.min_lr)
    base_lr = float(args.lr)

    def lr_lambda(epoch_idx: int) -> float:
        epoch = epoch_idx + 1
        if warmup_epochs > 0 and epoch <= warmup_epochs:
            return max(epoch / warmup_epochs, min_lr / max(base_lr, 1e-12))

        if total_epochs <= warmup_epochs:
            return min_lr / max(base_lr, 1e-12)

        progress = (epoch - warmup_epochs) / max(total_epochs - warmup_epochs, 1)
        progress = min(max(progress, 0.0), 1.0)
        cosine = 0.5 * (1.0 + np.cos(np.pi * progress))
        return (min_lr + (base_lr - min_lr) * cosine) / max(base_lr, 1e-12)

    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=lr_lambda)

def evaluate(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    stage_centroids: Dict[int, np.ndarray],
    target_bank: np.ndarray,
    target_keys: List[str],
) -> Dict[str, float]:
    model.eval()
    cosines: List[float] = []
    centroid_correct = 0
    exact_retrieval_correct = 0
    retrieval_at_5_correct = 0
    total = 0

    stages = sorted(stage_centroids.keys())
    centroid_matrix = np.stack([stage_centroids[s] for s in stages], axis=0)
    stage_to_col = {stage: idx for idx, stage in enumerate(stages)}

    with torch.no_grad():
        for batch in loader:
            src_embeddings = batch["src_embeddings"].to(device)
            src_stage_indices = batch["src_stage_indices"].to(device)
            src_padding_mask = batch["src_padding_mask"].to(device)
            tgt_embedding = batch["tgt_embedding"].to(device)

            pred = model(src_embeddings, src_stage_indices, src_padding_mask)
            batch_cos = torch.sum(pred * tgt_embedding, dim=-1)
            cosines.extend(batch_cos.detach().cpu().tolist())

            pred_np = pred.detach().cpu().numpy().astype(np.float32)
            centroid_scores = pred_np @ centroid_matrix.T
            pred_stage_cols = np.argmax(centroid_scores, axis=1)
            tgt_stages = batch["tgt_stage_idx"].detach().cpu().numpy()
            centroid_correct += int(np.sum(pred_stage_cols == np.array([stage_to_col[s] for s in tgt_stages])))

            retrieval_scores = pred_np @ target_bank.T
            retrieval_idx = np.argmax(retrieval_scores, axis=1)
            topk = min(5, retrieval_scores.shape[1])
            retrieval_topk_idx = np.argpartition(retrieval_scores, -topk, axis=1)[:, -topk:]
            batch_keys = batch["transition_key"]
            exact_retrieval_correct += sum(target_keys[idx] == key for idx, key in zip(retrieval_idx, batch_keys))
            retrieval_at_5_correct += sum(
                key in {target_keys[idx] for idx in row_idx}
                for row_idx, key in zip(retrieval_topk_idx, batch_keys)
            )
            total += pred_np.shape[0]

    return {
        "mean_target_cosine": float(np.mean(cosines)) if cosines else float("nan"),
        "centroid_stage_accuracy": float(centroid_correct / max(total, 1)),
        "exact_target_retrieval_at_1": float(exact_retrieval_correct / max(total, 1)),
        "exact_target_retrieval_at_5": float(retrieval_at_5_correct / max(total, 1)),
        "num_samples": int(total),
    }


def metric_value(metrics: Dict[str, float], args: argparse.Namespace) -> float:
    selection_metric = args.selection_metric
    if selection_metric == "retrieval_at_1":
        return float(metrics["exact_target_retrieval_at_1"])
    if selection_metric == "cosine":
        return float(metrics["mean_target_cosine"])
    if selection_metric == "blended":
        return (
            float(args.blend_retrieval_weight) * float(metrics["exact_target_retrieval_at_1"])
            + float(args.blend_cosine_weight) * float(metrics["mean_target_cosine"])
        )
    raise ValueError(f"Unknown selection metric: {selection_metric}")


def main() -> None:
    args = parse_args()
    set_seed(args.seed)

    embeddings_path = Path(args.embeddings_npz)
    aux_embedding_paths = [Path(path) for path in args.aux_embeddings_npz]
    embedding_paths = [embeddings_path, *aux_embedding_paths]
    output_dir = Path(args.output_dir)
    ensure_dir(output_dir)
    device = torch.device(args.device)

    lookup, embedding_dim, embedding_alignment = load_combined_embedding_lookup(
        embedding_paths,
        alignment=args.embedding_key_alignment,
    )
    frame_rows = load_frame_rows(Path(args.manifest_frames), lookup)
    examples, skipped_noncontiguous = build_prefix_examples(frame_rows, args.context_window)
    splits = split_rows(examples)
    feature_transform = resolve_feature_transform(args.feature_transform, embeddings_path)
    stage_head_mode = resolve_stage_head_mode(args.stage_head_mode, args.disable_stage_specific_output_heads, embeddings_path)

    if feature_transform == "standardize":
        feature_mean, feature_std = fit_standardization(splits["train"])
        splits = {name: transform_rows_standardize(rows, feature_mean, feature_std) for name, rows in splits.items()}
        feature_components = None
        feature_scales = None
        transformed_embedding_dim = embedding_dim
    elif feature_transform in {"pca", "pca_whiten"}:
        pca_transform = fit_pca_transform(
            splits["train"],
            output_dim=args.feature_output_dim,
            whiten=(feature_transform == "pca_whiten"),
        )
        feature_mean = np.asarray(pca_transform["mean"], dtype=np.float32)
        feature_components = np.asarray(pca_transform["components"], dtype=np.float32)
        feature_scales = np.asarray(pca_transform["scales"], dtype=np.float32)
        feature_std = None
        transformed_embedding_dim = int(pca_transform["output_dim"])
        splits = {
            name: transform_rows_pca(rows, feature_mean, feature_components, feature_scales)
            for name, rows in splits.items()
        }
        np.savez_compressed(
            output_dir / "feature_transform.npz",
            mean=feature_mean,
            components=feature_components,
            scales=feature_scales,
            output_dim=np.array([transformed_embedding_dim], dtype=np.int32),
            whiten=np.array([1 if feature_transform == "pca_whiten" else 0], dtype=np.int8),
        )
    else:
        feature_mean = None
        feature_std = None
        feature_components = None
        feature_scales = None
        transformed_embedding_dim = embedding_dim

    max_stage_idx = max(int(row["tgt_stage_idx"]) for row in examples)
    max_seq_len = max(int(np.asarray(row["src_stage_indices"]).shape[0]) for row in examples)

    datasets = {
        "train": PrefixTransitionDataset(splits["train"]),
        "val": PrefixTransitionDataset(splits["val"]),
        "test": PrefixTransitionDataset(splits["test"]),
    }
    pin_memory = device.type == "cuda"
    loaders = {
        "train": DataLoader(
            datasets["train"],
            batch_size=args.batch_size,
            shuffle=True,
            num_workers=args.num_workers,
            pin_memory=pin_memory,
            collate_fn=collate_prefix_batch,
        ),
        "val": DataLoader(
            datasets["val"],
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=pin_memory,
            collate_fn=collate_prefix_batch,
        ),
        "test": DataLoader(
            datasets["test"],
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=pin_memory,
            collate_fn=collate_prefix_batch,
        ),
    }

    model = TransitionSequenceTransformer(
        embedding_dim=transformed_embedding_dim,
        model_dim=args.model_dim,
        num_layers=args.num_layers,
        num_heads=args.num_heads,
        ff_dim=args.ff_dim,
        dropout=args.dropout,
        num_stages=max_stage_idx + 1,
        max_seq_len=max_seq_len,
        stage_embed_dim=args.stage_embed_dim,
        stage_specific_output_heads=(stage_head_mode == "stage-specific"),
    ).to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    scheduler = make_lr_scheduler(optimizer, args)
    best_state = None
    best_val_score = -float("inf")
    epochs_without_improvement = 0
    history: List[Dict[str, float]] = []

    val_centroids, val_bank, val_keys = build_eval_artifacts(splits["val"])

    for epoch in range(1, args.epochs + 1):
        train_metrics = train_one_epoch(model, loaders["train"], optimizer, device, args)
        val_metrics = evaluate(model, loaders["val"], device, val_centroids, val_bank, val_keys)
        val_score = metric_value(val_metrics, args)
        epoch_summary = {
            "epoch": float(epoch),
            "train_loss": train_metrics["loss"],
            "train_cosine_loss": train_metrics["cosine_loss"],
            "train_contrastive_loss": train_metrics["contrastive_loss"],
            "train_margin_loss": train_metrics["margin_loss"],
            "val_mean_target_cosine": val_metrics["mean_target_cosine"],
            "val_centroid_stage_accuracy": val_metrics["centroid_stage_accuracy"],
            "val_exact_target_retrieval_at_1": val_metrics["exact_target_retrieval_at_1"],
            "val_exact_target_retrieval_at_5": val_metrics["exact_target_retrieval_at_5"],
            "val_selection_score": val_score,
            "lr": float(optimizer.param_groups[0]["lr"]),
        }
        history.append(epoch_summary)

        if val_score > best_val_score:
            best_val_score = val_score
            best_state = {key: value.detach().cpu().clone() for key, value in model.state_dict().items()}
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

        scheduler.step()

        if epochs_without_improvement >= args.patience:
            break

    if best_state is None:
        raise RuntimeError("Training did not produce a valid checkpoint.")

    model.load_state_dict(best_state)
    torch.save(best_state, output_dir / "best_model.pt")

    train_centroids, train_bank, train_keys = build_eval_artifacts(splits["train"])
    test_centroids, test_bank, test_keys = build_eval_artifacts(splits["test"])
    train_metrics = evaluate(model, loaders["train"], device, train_centroids, train_bank, train_keys)
    val_metrics = evaluate(model, loaders["val"], device, val_centroids, val_bank, val_keys)
    test_metrics = evaluate(model, loaders["test"], device, test_centroids, test_bank, test_keys)

    summary = {
        "embeddings_npz": args.embeddings_npz,
        "aux_embeddings_npz": [str(path) for path in aux_embedding_paths],
        "embedding_sources": [str(path) for path in embedding_paths],
        "embedding_alignment": embedding_alignment,
        "manifest_frames": args.manifest_frames,
        "device": str(device),
        "model_config": {
            "model_dim": args.model_dim,
            "num_layers": args.num_layers,
            "num_heads": args.num_heads,
            "ff_dim": args.ff_dim,
            "stage_embed_dim": args.stage_embed_dim,
            "dropout": args.dropout,
            "context_window": args.context_window,
            "num_stages": max_stage_idx + 1,
            "max_seq_len": max_seq_len,
            "stage_head_mode": stage_head_mode,
            "stage_specific_output_heads": (stage_head_mode == "stage-specific"),
        },
        "training_config": {
            "batch_size": args.batch_size,
            "epochs": args.epochs,
            "lr": args.lr,
            "min_lr": args.min_lr,
            "weight_decay": args.weight_decay,
            "feature_transform": feature_transform,
            "feature_output_dim": args.feature_output_dim,
            "embedding_key_alignment": args.embedding_key_alignment,
            "context_window": args.context_window,
            "grad_clip_norm": args.grad_clip_norm,
            "cosine_weight": args.cosine_weight,
            "contrastive_weight": args.contrastive_weight,
            "margin_loss_weight": args.margin_loss_weight,
            "margin_loss_value": args.margin_loss_value,
            "temperature": args.temperature,
            "source_feature_dropout": args.source_feature_dropout,
            "source_noise_std": args.source_noise_std,
            "stage_head_mode": stage_head_mode,
            "selection_metric": args.selection_metric,
            "blend_retrieval_weight": args.blend_retrieval_weight,
            "blend_cosine_weight": args.blend_cosine_weight,
            "patience": args.patience,
            "lr_warmup_epochs": args.lr_warmup_epochs,
            "seed": args.seed,
        },
        "feature_stats": {
            "mean_norm": float(np.linalg.norm(feature_mean)) if feature_mean is not None else None,
            "std_mean": float(np.mean(feature_std)) if feature_std is not None else None,
            "std_min": float(np.min(feature_std)) if feature_std is not None else None,
            "std_max": float(np.max(feature_std)) if feature_std is not None else None,
            "components_shape": list(feature_components.shape) if feature_components is not None else None,
            "scale_mean": float(np.mean(feature_scales)) if feature_scales is not None else None,
            "scale_min": float(np.min(feature_scales)) if feature_scales is not None else None,
            "scale_max": float(np.max(feature_scales)) if feature_scales is not None else None,
            "transform_path": str(output_dir / "feature_transform.npz") if feature_components is not None else None,
        },
        "num_train": len(splits["train"]),
        "num_val": len(splits["val"]),
        "num_test": len(splits["test"]),
        "embedding_dim": transformed_embedding_dim,
        "raw_embedding_dim": embedding_dim,
        "skipped_noncontiguous_examples": skipped_noncontiguous,
        "best_val_selection_score": best_val_score,
        "train_metrics": train_metrics,
        "val_metrics": val_metrics,
        "test_metrics": test_metrics,
        "history": history,
    }
    write_json(output_dir / "metrics.json", summary)

    print("Transition transformer training complete")
    print(f"Train / Val / Test: {len(splits['train'])} / {len(splits['val'])} / {len(splits['test'])}")
    print(f"Max prefix length:   {max_seq_len}")
    print(f"Best val score:      {best_val_score:.4f} ({args.selection_metric})")
    print(f"Test cosine:         {test_metrics['mean_target_cosine']:.4f}")
    print(f"Test stage acc:      {test_metrics['centroid_stage_accuracy']:.4f}")
    print(f"Test retrieval@1:    {test_metrics['exact_target_retrieval_at_1']:.4f}")
    print(f"Test retrieval@5:    {test_metrics['exact_target_retrieval_at_5']:.4f}")
    print(f"Output dir:          {output_dir}")


if __name__ == "__main__":
    main()
