import argparse
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset

from learning_utils import TransitionMLP, default_device, load_embedding_archive, normalize_rows
from script_utils import LEARNING_ROOT, ensure_dir, read_csv_rows, write_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train a latent next-stage baseline on CLIP embeddings.")
    parser.add_argument(
        "--embeddings-npz",
        default=str(LEARNING_ROOT / "embeddings" / "clip_embeddings_all.npz"),
        help="Path to embedding .npz generated by extract_clip_embeddings.py",
    )
    parser.add_argument(
        "--transitions-csv",
        default=str(LEARNING_ROOT / "manifest_transitions.csv"),
        help="Path to transition manifest CSV from build_manifest.py",
    )
    parser.add_argument(
        "--output-dir",
        default=str(LEARNING_ROOT / "ar_baseline"),
        help="Output directory for training artifacts",
    )
    parser.add_argument("--device", default=default_device(), help="Training device")
    parser.add_argument("--batch-size", type=int, default=64, help="Mini-batch size")
    parser.add_argument("--epochs", type=int, default=200, help="Maximum number of epochs")
    parser.add_argument("--lr", type=float, default=1e-3, help="Learning rate")
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="AdamW weight decay")
    parser.add_argument("--hidden-dim", type=int, default=512, help="Hidden width for the MLP predictor")
    parser.add_argument("--stage-embed-dim", type=int, default=16, help="Learned source-stage embedding size")
    parser.add_argument("--dropout", type=float, default=0.1, help="Dropout in the MLP predictor")
    parser.add_argument("--patience", type=int, default=25, help="Early stopping patience on validation cosine")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    return parser.parse_args()


def set_seed(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_embedding_lookup(path: Path) -> Tuple[Dict[Tuple[str, int], np.ndarray], int]:
    data = load_embedding_archive(path, normalize=True)
    embeddings = data["embeddings"]
    stems = data["stems"]
    stage_indices = data["stage_indices"]
    lookup: Dict[Tuple[str, int], np.ndarray] = {}
    for stem, stage_idx, emb in zip(stems, stage_indices, embeddings):
        lookup[(str(stem), int(stage_idx))] = emb

    return lookup, int(embeddings.shape[1])


def load_transitions(path: Path, lookup: Dict[Tuple[str, int], np.ndarray]) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    for row in read_csv_rows(path, description="Transition manifest"):
        stem = str(row["stem"])
        src_stage = int(row["src_stage_idx"])
        tgt_stage = int(row["tgt_stage_idx"])
        src_key = (stem, src_stage)
        tgt_key = (stem, tgt_stage)
        if src_key not in lookup or tgt_key not in lookup:
            raise KeyError(f"Missing embedding lookup for transition {row['transition_key']}")

        rows.append(
            {
                "stem": stem,
                "split": row["split"],
                "transition_key": row["transition_key"],
                "src_stage_idx": src_stage,
                "tgt_stage_idx": tgt_stage,
                "src_embedding": lookup[src_key],
                "tgt_embedding": lookup[tgt_key],
            }
        )

    if not rows:
        raise RuntimeError("No transition rows loaded.")
    return rows


class TransitionDataset(Dataset):
    def __init__(self, rows: List[Dict[str, object]]):
        self.rows = rows

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, idx: int):
        row = self.rows[idx]
        return {
            "src_embedding": torch.from_numpy(np.asarray(row["src_embedding"], dtype=np.float32)),
            "tgt_embedding": torch.from_numpy(np.asarray(row["tgt_embedding"], dtype=np.float32)),
            "src_stage_idx": torch.tensor(int(row["src_stage_idx"]), dtype=torch.long),
            "tgt_stage_idx": torch.tensor(int(row["tgt_stage_idx"]), dtype=torch.long),
            "transition_key": str(row["transition_key"]),
        }


def split_rows(rows: List[Dict[str, object]]) -> Dict[str, List[Dict[str, object]]]:
    out = {"train": [], "val": [], "test": []}
    for row in rows:
        split = str(row["split"])
        if split in out:
            out[split].append(row)
    for split_name, split_rows in out.items():
        if not split_rows:
            raise RuntimeError(f"No rows found for split: {split_name}")
    return out


def build_stage_centroids(rows: List[Dict[str, object]]) -> Dict[int, np.ndarray]:
    by_stage: Dict[int, List[np.ndarray]] = {}
    for row in rows:
        stage = int(row["tgt_stage_idx"])
        by_stage.setdefault(stage, []).append(np.asarray(row["tgt_embedding"], dtype=np.float32))

    centroids: Dict[int, np.ndarray] = {}
    for stage, vecs in by_stage.items():
        stack = normalize_rows(np.stack(vecs, axis=0))
        centroid = stack.mean(axis=0, dtype=np.float32)
        centroid /= max(float(np.linalg.norm(centroid)), 1e-12)
        centroids[stage] = centroid.astype(np.float32)
    return centroids


def collect_target_bank(rows: List[Dict[str, object]]) -> Tuple[np.ndarray, List[str]]:
    embeddings = []
    keys = []
    for row in rows:
        embeddings.append(np.asarray(row["tgt_embedding"], dtype=np.float32))
        keys.append(str(row["transition_key"]))
    return normalize_rows(np.stack(embeddings, axis=0)), keys


def build_eval_artifacts(rows: List[Dict[str, object]]) -> Tuple[Dict[int, np.ndarray], np.ndarray, List[str]]:
    return build_stage_centroids(rows), *collect_target_bank(rows)


def train_one_epoch(model: nn.Module, loader: DataLoader, optimizer: torch.optim.Optimizer, device: torch.device) -> float:
    model.train()
    losses: List[float] = []

    for batch in loader:
        src = batch["src_embedding"].to(device)
        tgt = batch["tgt_embedding"].to(device)
        src_stage = batch["src_stage_idx"].to(device)

        pred = model(src, src_stage)
        loss = 1.0 - torch.sum(pred * tgt, dim=-1).mean()

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        losses.append(float(loss.detach().cpu().item()))

    return float(np.mean(losses)) if losses else float("nan")


def evaluate(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    stage_centroids: Dict[int, np.ndarray],
    target_bank: np.ndarray,
    target_keys: List[str],
) -> Dict[str, float]:
    model.eval()
    cosines: List[float] = []
    centroid_correct = 0
    exact_retrieval_correct = 0
    total = 0

    stages = sorted(stage_centroids.keys())
    centroid_matrix = np.stack([stage_centroids[s] for s in stages], axis=0)
    stage_to_col = {stage: idx for idx, stage in enumerate(stages)}

    with torch.no_grad():
        for batch in loader:
            src = batch["src_embedding"].to(device)
            tgt = batch["tgt_embedding"].to(device)
            src_stage = batch["src_stage_idx"].to(device)

            pred = model(src, src_stage)
            batch_cos = torch.sum(pred * tgt, dim=-1)
            cosines.extend(batch_cos.detach().cpu().tolist())

            pred_np = pred.detach().cpu().numpy().astype(np.float32)
            centroid_scores = pred_np @ centroid_matrix.T
            pred_stage_cols = np.argmax(centroid_scores, axis=1)
            tgt_stages = batch["tgt_stage_idx"].detach().cpu().numpy()
            centroid_correct += int(np.sum(pred_stage_cols == np.array([stage_to_col[s] for s in tgt_stages])))

            retrieval_scores = pred_np @ target_bank.T
            retrieval_idx = np.argmax(retrieval_scores, axis=1)
            batch_keys = batch["transition_key"]
            exact_retrieval_correct += sum(target_keys[idx] == key for idx, key in zip(retrieval_idx, batch_keys))
            total += pred_np.shape[0]

    return {
        "mean_target_cosine": float(np.mean(cosines)) if cosines else float("nan"),
        "centroid_stage_accuracy": float(centroid_correct / max(total, 1)),
        "exact_target_retrieval_at_1": float(exact_retrieval_correct / max(total, 1)),
        "num_samples": int(total),
    }


def main() -> None:
    args = parse_args()
    set_seed(args.seed)

    output_dir = Path(args.output_dir)
    ensure_dir(output_dir)
    device = torch.device(args.device)

    lookup, embedding_dim = load_embedding_lookup(Path(args.embeddings_npz))
    rows = load_transitions(Path(args.transitions_csv), lookup)
    splits = split_rows(rows)

    datasets = {name: TransitionDataset(split_rows_) for name, split_rows_ in splits.items()}
    loaders = {
        "train": DataLoader(datasets["train"], batch_size=args.batch_size, shuffle=True),
        "val": DataLoader(datasets["val"], batch_size=args.batch_size, shuffle=False),
        "test": DataLoader(datasets["test"], batch_size=args.batch_size, shuffle=False),
    }

    max_stage_idx = max(int(row["tgt_stage_idx"]) for row in rows)
    model = TransitionMLP(
        embedding_dim=embedding_dim,
        hidden_dim=args.hidden_dim,
        stage_embed_dim=args.stage_embed_dim,
        dropout=args.dropout,
        num_stages=max_stage_idx + 1,
    ).to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    best_state = None
    best_val_cosine = -float("inf")
    epochs_without_improvement = 0
    history: List[Dict[str, float]] = []

    val_centroids, val_bank, val_keys = build_eval_artifacts(splits["val"])

    for epoch in range(1, args.epochs + 1):
        train_loss = train_one_epoch(model, loaders["train"], optimizer, device)
        val_metrics = evaluate(model, loaders["val"], device, val_centroids, val_bank, val_keys)
        epoch_summary = {
            "epoch": float(epoch),
            "train_loss": train_loss,
            "val_mean_target_cosine": val_metrics["mean_target_cosine"],
            "val_centroid_stage_accuracy": val_metrics["centroid_stage_accuracy"],
            "val_exact_target_retrieval_at_1": val_metrics["exact_target_retrieval_at_1"],
        }
        history.append(epoch_summary)

        if val_metrics["mean_target_cosine"] > best_val_cosine:
            best_val_cosine = val_metrics["mean_target_cosine"]
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

        if epochs_without_improvement >= args.patience:
            break

    if best_state is None:
        raise RuntimeError("Training did not produce a valid checkpoint.")

    model.load_state_dict(best_state)
    torch.save(best_state, output_dir / "best_model.pt")

    test_centroids, test_bank, test_keys = build_eval_artifacts(splits["test"])
    test_metrics = evaluate(model, loaders["test"], device, test_centroids, test_bank, test_keys)
    train_centroids, train_bank, train_keys = build_eval_artifacts(splits["train"])
    train_metrics = evaluate(model, loaders["train"], device, train_centroids, train_bank, train_keys)
    final_val_metrics = evaluate(model, loaders["val"], device, val_centroids, val_bank, val_keys)

    summary = {
        "embeddings_npz": args.embeddings_npz,
        "transitions_csv": args.transitions_csv,
        "device": str(device),
        "model_config": {
            "hidden_dim": args.hidden_dim,
            "stage_embed_dim": args.stage_embed_dim,
            "dropout": args.dropout,
            "num_stages": max_stage_idx + 1,
        },
        "num_train": len(splits["train"]),
        "num_val": len(splits["val"]),
        "num_test": len(splits["test"]),
        "embedding_dim": embedding_dim,
        "best_val_mean_target_cosine": best_val_cosine,
        "train_metrics": train_metrics,
        "val_metrics": final_val_metrics,
        "test_metrics": test_metrics,
        "history": history,
    }

    write_json(output_dir / "metrics.json", summary)

    print("Transition baseline training complete")
    print(f"Train / Val / Test: {len(splits['train'])} / {len(splits['val'])} / {len(splits['test'])}")
    print(f"Best val cosine:    {best_val_cosine:.4f}")
    print(f"Test cosine:        {test_metrics['mean_target_cosine']:.4f}")
    print(f"Test stage acc:     {test_metrics['centroid_stage_accuracy']:.4f}")
    print(f"Test retrieval@1:   {test_metrics['exact_target_retrieval_at_1']:.4f}")
    print(f"Output dir:         {output_dir}")


if __name__ == "__main__":
    main()
